### ISSUE TITLE
Gallery index crashes for partial translations

### ISSUE THREAD

**Issue by smurfix** [getnikola/nikola#1971] opened 2015-08-24 14:02 UTC
My (German) site has default and "en" language enabled.
```
mkdir galleries/test/
echo foo >galleries/test/index.txt
nikola build
```
crashes:
```
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/doit/doit_cmd.py", line 165, in run
    return command.parse_execute(args)
  File "/usr/lib/python2.7/dist-packages/doit/cmd_base.py", line 122, in parse_execute
    return self.execute(params, args)
  File "/usr/lib/python2.7/dist-packages/doit/cmd_base.py", line 405, in execute
    return self._execute(**exec_params)
  File "/usr/lib/python2.7/dist-packages/doit/cmd_run.py", line 239, in _execute
    return runner.run_all(self.control.task_dispatcher())
  File "/usr/lib/python2.7/dist-packages/doit/runner.py", line 238, in run_all
    self.run_tasks(task_dispatcher)
  File "/usr/lib/python2.7/dist-packages/doit/runner.py", line 205, in run_tasks
    self.process_task_result(node, catched_excp)
  File "/usr/lib/python2.7/dist-packages/doit/runner.py", line 176, in process_task_result
    self.dep_manager.save_success(task)
  File "/usr/lib/python2.7/dist-packages/doit/dependency.py", line 484, in save_success
    state = self.checker.get_state(dep, self._get(task.name, dep))
  File "/usr/lib/python2.7/dist-packages/doit/dependency.py", line 403, in get_state
    timestamp = os.path.getmtime(dep)
  File "/usr/lib/python2.7/genericpath.py", line 54, in getmtime
    return os.stat(filename).st_mtime
OSError: [Errno 2] No such file or directory: 'cache/galleries/test/index.en.html'
```

**Comment by felixfontein** [comment] 2015-08-25 20:15
I cannot reproduce that with current Nikola master.
Anyway, this looks like something isn't right with doit. Can the user read/write to all subdirectories of the current directory?

**Comment by ralsina** [comment] 2015-09-11 13:18
So, this was probably having an old base theme copied into themes/ ... at least that's what caused something very similar.

**Comment by ralsina** [comment] 2015-09-11 13:19
I am going to close it, but feel free to reopen if it's still happening with master/7.7.0 or if it's not an outdated theme.

**Closed by ralsina** 2015-09-11 13:19 UTC
Labels: awaiting response
