### ISSUE TITLE
Inconsistent .doit.db file name

### ISSUE THREAD

**Issue by qobilidop** [getnikola/nikola#2933] opened 2017-12-06 07:57 UTC
### Environment (if reporting a bug)

**Python Version:** 3.6.3

**Nikola Version:** 7.8.10

**doit Version:** 0.30.3

**Operating System:** macOS Sierra 10.12.6

### Description:

I simply create an empty site and build:
```bash
nikola init -q site
cd site
nikola build
```
Instead of `.doit.db`, I get `.doit.db.db`.

**Comment by qobilidop** [comment] 2017-12-06 08:09
I see this strange file name appears in #2186 and #2499 too. But I don't see the issue explicitly addressed.

**Comment by Kwpolska** [comment] 2017-12-06 18:05
@schettino72, any ideas?

This seems like a random glitch. It doesn’t seem to be important, perhaps try removing it and see what happens next?

**Comment by qobilidop** [comment] 2017-12-06 18:20
Yeah, I simply put it in .gitignore and it's not affecting anything. For me, it's not an urgent issue to solve at all. Thanks for looking at it @Kwpolska

**Comment by schettino72** [comment] 2017-12-06 19:20
This is a problem with `doit`. The problem is that `doit` uses python stdlib `dbm`. It will automatically choose a `dbm` implementation that is available on your machine. Depending of the `dbm` implementation it might create a single file or several files.

`doit` logic is quite simplistic by appending `.db` to the database name. the problem is that some implementations of `dbm` will also add this `.db` extension... so doit would need to be aware of the naming conventions of each implementation... and I never really bothered.

So it is a minor issue, if anyone wants to fix it i would be glad to receive a pull-request.

**Comment by Kwpolska** [comment] 2017-12-06 19:28
Closing this due to being a minor, rare, third-party bug.

**Closed by Kwpolska** 2017-12-06 19:28 UTC
Labels: minor, someone else's bug
