### ISSUE TITLE
Module not found on fresh install 

### ISSUE THREAD

**Issue by el-barto** [getnikola/nikola#3614] opened 2022-04-22 19:24 UTC
I tried a fresh install of Nikola following the Getting Started guide and got the following error:
```
(nikola) elbarto@spielberg:~/nikola$ nikola init personal_website
Traceback (most recent call last):
  File "/home/elbarto/nikola/bin/nikola", line 5, in <module>
    from nikola.__main__ import main
  File "/home/elbarto/nikola/lib/python3.9/site-packages/nikola/__main__.py", line 39, in <module>
    from doit.cmd_auto import Auto as DoitAuto
ModuleNotFoundError: No module named 'doit.cmd_auto'
```

The steps to get to this error were:

```
elbarto@spielberg:~$ python3 -m venv nikola
elbarto@spielberg:~$ cd nikola
elbarto@spielberg:~/nikola$ source bin/activate
(nikola) elbarto@spielberg:~/nikola$ bin/python -m pip install -U pip setuptools wheel
(nikola) elbarto@spielberg:~/nikola$ bin/python -m pip install -U "Nikola[extras]"
```

**System details:**
OS: Kubuntu 21.04
Python version: 3.9.5

**Comment by Kwpolska** [comment] 2022-04-22 19:26
This is an incompatibility in `doit==0.36.0`, sorry for that. A new version of Nikola with a fix will come out tomorrow. Or you can temporarily downgrade doit to a working version with `python -m pip install 'doit<0.36.0'`.

Closing as duplicate of #3612.

**Closed by Kwpolska** 2022-04-22 19:26 UTC
Labels: duplicate

**Comment by Kwpolska** [comment] 2022-04-23 15:54
Nikola v8.2.1 is out with a fix for this issue.
