### ISSUE TITLE
RSS feed generation fails with 8.0.0b1

### ISSUE THREAD

**Issue by jmcp** [getnikola/nikola#3077] opened 2018-05-08 07:59 UTC
### Environment (if reporting a bug)

**Python Version:** 3.5

**Nikola Version:** 8.0.0b1

**Operating System:** Solaris 11.4

### Description:

Kicking the tires with 8.0.0b1 ,I used the default conf.py which includes `GENERATE_RSS = True`.
While running `nikola build` the process died at the end of the gallery generation process:

```
[elided]
[2018-05-08T07:50:08Z] DEBUG: MARKDOWN: Successfully loaded extension "markdown.extensions.extra.ExtraExtension".
Scanning posts........done!
[2018-05-08T07:50:09Z] DEBUG: render_galleries: Using galleries/home/new_pool/metadata.yml for gallery galleries/home/new_pool
[2018-05-08T07:50:09Z] DEBUG: render_galleries: Using galleries/cycling/2018-02-18-coottha-yay/metadata.yml for gallery galleries/cycling/2018-02-18-coottha-yay
[2018-05-08T07:50:09Z] DEBUG: render_galleries: Using galleries/tourism/hmas_parramatta/metadata.yml for gallery galleries/tourism/hmas_parramatta
.  render_galleries:output/galleries/home/new_pool/index.html
.  render_galleries:output/galleries/cycling/2018-02-18-coottha-yay/rss.xml
TaskError - taskid:render_galleries:output/galleries/cycling/2018-02-18-coottha-yay/rss.xml
PythonAction Error
Traceback (most recent call last):
  File "/space/builds/jmcp/web/nikola/v-3.5/lib/python3.5/site-packages/doit/action.py", line 424, in execute
    returned_value = self.py_callable(*self.args, **kwargs)
  File "/space/builds/jmcp/web/nikola/v-3.5/lib/python3.5/site-packages/nikola/plugins/task/galleries.py", line 736, in gallery_rss
    items.append(rss.RSSItem(**args))
  File "/space/builds/jmcp/web/nikola/v-3.5/lib/python3.5/site-packages/PyRSS2Gen.py", line 410, in __init__
    "must define at least one of 'title' or 'description'")
TypeError: must define at least one of 'title' or 'description'

########################################
render_galleries:output/galleries/cycling/2018-02-18-coottha-yay/rss.xml <stdout>:

```

**Comment by jmcp** [comment] 2018-05-08 08:07
I tried creating an index.txt which contained both a title and description in reST, but there was no difference to the error from the rss generator

**Comment by Kwpolska** [comment] 2018-05-08 21:40
Line 410 in PyRSS2Gen.py is in `RSSItem`’s constructor. 
```py
        if title is None and description is None:
            raise TypeError(
                "must define at least one of 'title' or 'description'")
```

This seems to be a duplicate of #3076.

**Closed** 2018-05-08 22:50 UTC
Labels: duplicate, user error
