### ISSUE TITLE
Strange rendering of markdown pages

### ISSUE THREAD

**Issue by hardening** [getnikola/nikola#3191] opened 2018-12-13 18:27 UTC
As discussed on IRC: I'm running last nikola (7d142c907b761db03eea160956635b94503b1a8b), with python 3.6.7 (Ubuntu 18.04).

When generating my site https://github.com/hardening/hardening-consulting.com (mdx_video module required), I noticed a strange rendering bug, if I change the beginning of the post (https://github.com/hardening/hardening-consulting.com/blob/master/posts/2018-twisted-tricks.wp) to

```
<img class="alignright" src="/images/twisted.png" width="100px">

En travaillant sur [topka][topka], j'ai eu l'occasion d'utiliser [twisted][twisted]. Les tutoriaux de twisted
```
(`&nbsp;` removed) then the `img` tag is not rendered in the output page. 

Even more strange, if I move lower the `img` in the post, then `img` is not rendered and the text around is removed. Most of my other posts have the same structure and work fine.

**Comment by hardening** [comment] 2018-12-31 10:45
just curious, is it reproducible elsewhere ?

**Comment by Kwpolska** [comment] 2018-12-31 13:57
Reproduced. It looks like the first paragraph gets removed. This should not happen with 2-file posts.

**Comment by Kwpolska** [comment] 2018-12-31 18:55
This was happening only in non-translated posts on your blog. Since Nikola couldn’t find a `.en.meta` file, it set the status for the post to one-file. In one-file mode, we delete everything before the first empty line in output to hide the metadata from view.

Fixed by making the one-file decision only basing on the default language, unless we manage to find a non-default two-file post. PR #3195.

**Comment by hardening** [comment] 2019-01-01 11:32
I can confirm that when I've created the English translation, the bug disappeared.

**Comment by Kwpolska** [comment] 2019-01-01 13:01
Does the PR fix it for you (without an English translation)?

**Closed** 2019-01-02 08:44 UTC
Labels: PR exists, bug, i18n
