### ISSUE TITLE
Auto don’t like double-reload

### ISSUE THREAD

**Issue by Aeyoun** [getnikola/nikola#1906] opened 2015-07-23 13:43 UTC
1. Serve with auto
2. Open in browser and press ctrl+r, ctrl+r (or get impatient with auto’s iniated reload while rebuilding and hit ctrl+r just once as it also starts refreshing)

```pytb
Traceback (most recent call last):
      File "/usr/lib/python3.4/wsgiref/handlers.py", line 138, in run
        self.finish_response()
      File "/usr/local/lib/python3.4/dist-packages/ws4py/server/wsgirefserver.py", line 71, in finish_response
        SimpleHandler.finish_response(self)
      File "/usr/lib/python3.4/wsgiref/handlers.py", line 180, in finish_response
        self.write(data)
      File "/usr/lib/python3.4/wsgiref/handlers.py", line 274, in write
        self.send_headers()
      File "/usr/lib/python3.4/wsgiref/handlers.py", line 332, in send_headers
        self.send_preamble()
      File "/usr/lib/python3.4/wsgiref/handlers.py", line 255, in send_preamble
        ('Date: %s\r\n' % format_date_time(time.time())).encode('iso-8859-1')
      File "/usr/lib/python3.4/wsgiref/handlers.py", line 453, in _write
        self.stdout.write(data)
      File "/usr/lib/python3.4/socket.py", line 391, in write
        return self._sock.send(b)
    BrokenPipeError: [Errno 32] Broken pipe
    ----------------------------------------
    Exception happened during processing of request from ('127.0.0.1', 45759)
    Traceback (most recent call last):
      File "/usr/lib/python3.4/wsgiref/handlers.py", line 138, in run
        self.finish_response()
      File "/usr/local/lib/python3.4/dist-packages/ws4py/server/wsgirefserver.py", line 71, in finish_response
        SimpleHandler.finish_response(self)
      File "/usr/lib/python3.4/wsgiref/handlers.py", line 180, in finish_response
        self.write(data)
      File "/usr/lib/python3.4/wsgiref/handlers.py", line 274, in write
        self.send_headers()
      File "/usr/lib/python3.4/wsgiref/handlers.py", line 332, in send_headers
        self.send_preamble()
      File "/usr/lib/python3.4/wsgiref/handlers.py", line 255, in send_preamble
        ('Date: %s\r\n' % format_date_time(time.time())).encode('iso-8859-1')
      File "/usr/lib/python3.4/wsgiref/handlers.py", line 453, in _write
        self.stdout.write(data)
      File "/usr/lib/python3.4/socket.py", line 391, in write
        return self._sock.send(b)
    BrokenPipeError: [Errno 32] Broken pipe
    During handling of the above exception, another exception occurred:
    Traceback (most recent call last):
      File "/usr/lib/python3.4/socketserver.py", line 305, in _handle_request_noblock
        self.process_request(request, client_address)
      File "/usr/lib/python3.4/socketserver.py", line 331, in process_request
        self.finish_request(request, client_address)
      File "/usr/lib/python3.4/socketserver.py", line 344, in finish_request
        self.RequestHandlerClass(request, client_address, self)
      File "/usr/lib/python3.4/socketserver.py", line 669, in __init__
        self.handle()
      File "/usr/local/lib/python3.4/dist-packages/ws4py/server/wsgirefserver.py", line 95, in handle
        handler.run(self.server.get_app())
      File "/usr/lib/python3.4/wsgiref/handlers.py", line 141, in run
        self.handle_error()
      File "/usr/lib/python3.4/wsgiref/handlers.py", line 368, in handle_error
        self.finish_response()
      File "/usr/local/lib/python3.4/dist-packages/ws4py/server/wsgirefserver.py", line 71, in finish_response
        SimpleHandler.finish_response(self)
      File "/usr/lib/python3.4/wsgiref/handlers.py", line 180, in finish_response
        self.write(data)
      File "/usr/lib/python3.4/wsgiref/handlers.py", line 274, in write
        self.send_headers()
      File "/usr/lib/python3.4/wsgiref/handlers.py", line 331, in send_headers
        if not self.origin_server or self.client_is_modern():
      File "/usr/lib/python3.4/wsgiref/handlers.py", line 344, in client_is_modern
        return self.environ['SERVER_PROTOCOL'].upper() != 'HTTP/0.9'
    TypeError: 'NoneType' object is not subscriptable

**Comment by ralsina** [comment] 2015-07-31 00:42
I can't reproduce this at all, it's working solid for me.

**Comment by Kwpolska** [comment] 2015-07-31 07:28
I can. Python 3.4.3, slow magnetic hard drive (if that matters), mashing Ctrl+R while the site is rebuilding and trying to reload (took me a couple tries though).

```pytb
[2015-07-31T07:20:45Z] INFO: auto: REBUILDING SITE (from posts/1.rst)
[2015-07-31T07:20:46Z] INFO: ws4py: Terminating websocket [Local => 127.0.0.1:8000 | Remote => 127.0.0.1:48982]
[2015-07-31T07:20:46Z] INFO: ws4py: Managing websocket [Local => 127.0.0.1:8000 | Remote => 127.0.0.1:48993]
[2015-07-31T07:20:46Z] INFO: auto: <--- {'snipver': 1, 'protocols': ['http://livereload.com/protocols/official-6', 'http://livereload.com/protocols/official-7'], 'command': 'hello', 'ver': '2.2.1'}
[2015-07-31T07:20:46Z] INFO: auto: ---> {"protocols": ["http://livereload.com/protocols/official-7"], "command": "hello", "serverName": "nikola-livereload"}
[2015-07-31T07:20:47Z] INFO: auto: <--- {'command': 'info', 'plugins': {'less': {'disable': False, 'version': '1.0'}}, 'url': 'http://localhost:8000/'}
[2015-07-31T07:20:47Z] INFO: auto: ****** Browser connected: http://localhost:8000/
[2015-07-31T07:20:47Z] INFO: auto: ****** sending 0 pending messages
[2015-07-31T07:20:47Z] INFO: ws4py: Terminating websocket [Local => 127.0.0.1:8000 | Remote => 127.0.0.1:48993]
Scanning posts....done!
.  render_tags:output/assets/js/tag_cloud_data.json
.  render_sources:output/posts/welcome-to-nikola.rst
.  render_posts:timeline_changes
.  render_posts:cache/posts/1.html
.  render_tags:output/categories/cat_nikola.html
.  render_tags:output/categories/nikola.html
.  render_tags:output/categories/demo.html
.  render_indexes:output/index.html
.  render_tags:output/categories/blog.html
.  render_tags:output/categories/python.html
.  generate_rss:output/rss.xml
.  render_tags:output/categories/demo.xml
.  render_tags:output/categories/blog.xml
.  render_tags:output/categories/python.xml
.  render_tags:output/categories/cat_nikola.xml
.  render_pages:output/posts/welcome-to-nikola.html
.  render_tags:output/categories/nikola.xml
.  sitemap:output/sitemap.xml

[2015-07-31T07:20:48Z] INFO: auto: REBUILDING SITE (from posts/1.rst)
[2015-07-31T07:20:48Z] INFO: ws4py: Managing websocket [Local => 127.0.0.1:8000 | Remote => 127.0.0.1:49004]
[2015-07-31T07:20:48Z] INFO: auto: <--- {'snipver': 1, 'protocols': ['http://livereload.com/protocols/official-6', 'http://livereload.com/protocols/official-7'], 'command': 'hello', 'ver': '2.2.1'}
[2015-07-31T07:20:48Z] INFO: auto: ---> {"protocols": ["http://livereload.com/protocols/official-7"], "command": "hello", "serverName": "nikola-livereload"}
[2015-07-31T07:20:48Z] INFO: auto: <--- {'command': 'info', 'plugins': {'less': {'disable': False, 'version': '1.0'}}, 'url': 'http://localhost:8000/'}
[2015-07-31T07:20:48Z] INFO: auto: ****** Browser connected: http://localhost:8000/
[2015-07-31T07:20:48Z] INFO: auto: ****** sending 0 pending messages
[2015-07-31T07:20:49Z] INFO: ws4py: Terminating websocket [Local => 127.0.0.1:8000 | Remote => 127.0.0.1:49004]
[2015-07-31T07:20:49Z] INFO: ws4py: Managing websocket [Local => 127.0.0.1:8000 | Remote => 127.0.0.1:49015]
[2015-07-31T07:20:49Z] INFO: auto: <--- {'snipver': 1, 'protocols': ['http://livereload.com/protocols/official-6', 'http://livereload.com/protocols/official-7'], 'command': 'hello', 'ver': '2.2.1'}
[2015-07-31T07:20:49Z] INFO: auto: ---> {"protocols": ["http://livereload.com/protocols/official-7"], "command": "hello", "serverName": "nikola-livereload"}
[2015-07-31T07:20:49Z] INFO: auto: <--- {'command': 'info', 'plugins': {'less': {'disable': False, 'version': '1.0'}}, 'url': 'http://localhost:8000/'}
[2015-07-31T07:20:49Z] INFO: auto: ****** Browser connected: http://localhost:8000/
[2015-07-31T07:20:49Z] INFO: auto: ****** sending 0 pending messages
Scanning posts....done!

[2015-07-31T07:20:50Z] INFO: auto: REFRESHING: output/assets/js/tag_cloud_data.json
[2015-07-31T07:20:50Z] INFO: auto: ---> /assets/js/tag_cloud_data.json
[2015-07-31T07:20:50Z] INFO: auto: REFRESHING: output/posts/welcome-to-nikola.rst
[2015-07-31T07:20:50Z] INFO: auto: ---> /posts/welcome-to-nikola.rst
[2015-07-31T07:20:50Z] INFO: auto: REFRESHING: output/categories/cat_nikola.html
[2015-07-31T07:20:50Z] INFO: auto: ---> /categories/cat_nikola.html
[2015-07-31T07:20:50Z] INFO: auto: REFRESHING: output/categories/nikola.html
[2015-07-31T07:20:50Z] INFO: auto: ---> /categories/nikola.html
[2015-07-31T07:20:50Z] INFO: auto: REFRESHING: output/categories/demo.html
[2015-07-31T07:20:50Z] INFO: auto: ---> /categories/demo.html
[2015-07-31T07:20:50Z] INFO: auto: REFRESHING: output/index.html
[2015-07-31T07:20:50Z] INFO: auto: ---> /index.html
[2015-07-31T07:20:50Z] INFO: auto: REFRESHING: output/categories/blog.html
[2015-07-31T07:20:50Z] INFO: auto: ---> /categories/blog.html
[2015-07-31T07:20:50Z] INFO: auto: REFRESHING: output/categories/python.html
[2015-07-31T07:20:50Z] INFO: auto: ---> /categories/python.html
[2015-07-31T07:20:50Z] INFO: auto: REFRESHING: output/rss.xml
[2015-07-31T07:20:50Z] INFO: auto: ---> /rss.xml
[2015-07-31T07:20:50Z] INFO: auto: REFRESHING: output/categories/demo.xml
[2015-07-31T07:20:50Z] INFO: auto: ---> /categories/demo.xml
[2015-07-31T07:20:50Z] INFO: auto: REFRESHING: output/categories/blog.xml
[2015-07-31T07:20:50Z] INFO: auto: ---> /categories/blog.xml
[2015-07-31T07:20:50Z] INFO: auto: REFRESHING: output/categories/python.xml
[2015-07-31T07:20:50Z] INFO: auto: ---> /categories/python.xml
Traceback (most recent call last):
[2015-07-31T07:20:50Z] INFO: auto: REFRESHING: output/categories/cat_nikola.xml
[2015-07-31T07:20:50Z] INFO: auto: ---> /categories/cat_nikola.xml
[2015-07-31T07:20:50Z] INFO: auto: REFRESHING: output/posts/welcome-to-nikola.html
[2015-07-31T07:20:50Z] INFO: auto: ---> /posts/welcome-to-nikola.html
[2015-07-31T07:20:50Z] INFO: auto: REFRESHING: output/categories/nikola.xml
[2015-07-31T07:20:50Z] INFO: auto: ---> /categories/nikola.xml
[2015-07-31T07:20:50Z] INFO: auto: REFRESHING: output/sitemap.xml
[2015-07-31T07:20:50Z] INFO: auto: ---> /sitemap.xml
  File "/usr/lib64/python3.4/wsgiref/handlers.py", line 138, in run
    self.finish_response()
  File "/home/kwpolska/virtualenvs/nikola-py3/lib/python3.4/site-packages/ws4py/server/wsgirefserver.py", line 71, in finish_response
    SimpleHandler.finish_response(self)
  File "/usr/lib64/python3.4/wsgiref/handlers.py", line 180, in finish_response
    self.write(data)
  File "/usr/lib64/python3.4/wsgiref/handlers.py", line 274, in write
    self.send_headers()
  File "/usr/lib64/python3.4/wsgiref/handlers.py", line 332, in send_headers
    self.send_preamble()
  File "/usr/lib64/python3.4/wsgiref/handlers.py", line 255, in send_preamble
    ('Date: %s\r\n' % format_date_time(time.time())).encode('iso-8859-1')
  File "/usr/lib64/python3.4/wsgiref/handlers.py", line 453, in _write
    self.stdout.write(data)
  File "/usr/lib64/python3.4/socket.py", line 394, in write
    return self._sock.send(b)
BrokenPipeError: [Errno 32] Broken pipe
----------------------------------------
Exception happened during processing of request from ('127.0.0.1', 49018)
Traceback (most recent call last):
  File "/usr/lib64/python3.4/wsgiref/handlers.py", line 138, in run
    self.finish_response()
  File "/home/kwpolska/virtualenvs/nikola-py3/lib/python3.4/site-packages/ws4py/server/wsgirefserver.py", line 71, in finish_response
    SimpleHandler.finish_response(self)
  File "/usr/lib64/python3.4/wsgiref/handlers.py", line 180, in finish_response
    self.write(data)
  File "/usr/lib64/python3.4/wsgiref/handlers.py", line 274, in write
    self.send_headers()
  File "/usr/lib64/python3.4/wsgiref/handlers.py", line 332, in send_headers
    self.send_preamble()
  File "/usr/lib64/python3.4/wsgiref/handlers.py", line 255, in send_preamble
    ('Date: %s\r\n' % format_date_time(time.time())).encode('iso-8859-1')
  File "/usr/lib64/python3.4/wsgiref/handlers.py", line 453, in _write
    self.stdout.write(data)
  File "/usr/lib64/python3.4/socket.py", line 394, in write
    return self._sock.send(b)
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib64/python3.4/socketserver.py", line 305, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/lib64/python3.4/socketserver.py", line 331, in process_request
    self.finish_request(request, client_address)
  File "/usr/lib64/python3.4/socketserver.py", line 344, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib64/python3.4/socketserver.py", line 673, in __init__
    self.handle()
  File "/home/kwpolska/virtualenvs/nikola-py3/lib/python3.4/site-packages/ws4py/server/wsgirefserver.py", line 95, in handle
    handler.run(self.server.get_app())
  File "/usr/lib64/python3.4/wsgiref/handlers.py", line 141, in run
    self.handle_error()
  File "/usr/lib64/python3.4/wsgiref/handlers.py", line 368, in handle_error
    self.finish_response()
  File "/home/kwpolska/virtualenvs/nikola-py3/lib/python3.4/site-packages/ws4py/server/wsgirefserver.py", line 71, in finish_response
    SimpleHandler.finish_response(self)
  File "/usr/lib64/python3.4/wsgiref/handlers.py", line 180, in finish_response
    self.write(data)
  File "/usr/lib64/python3.4/wsgiref/handlers.py", line 274, in write
    self.send_headers()
  File "/usr/lib64/python3.4/wsgiref/handlers.py", line 331, in send_headers
    if not self.origin_server or self.client_is_modern():
  File "/usr/lib64/python3.4/wsgiref/handlers.py", line 344, in client_is_modern
    return self.environ['SERVER_PROTOCOL'].upper() != 'HTTP/0.9'
TypeError: 'NoneType' object is not subscriptable
----------------------------------------
Traceback (most recent call last):
  File "/usr/lib64/python3.4/wsgiref/handlers.py", line 138, in run
    self.finish_response()
  File "/home/kwpolska/virtualenvs/nikola-py3/lib/python3.4/site-packages/ws4py/server/wsgirefserver.py", line 71, in finish_response
    SimpleHandler.finish_response(self)
  File "/usr/lib64/python3.4/wsgiref/handlers.py", line 180, in finish_response
    self.write(data)
  File "/usr/lib64/python3.4/wsgiref/handlers.py", line 274, in write
    self.send_headers()
  File "/usr/lib64/python3.4/wsgiref/handlers.py", line 332, in send_headers
    self.send_preamble()
  File "/usr/lib64/python3.4/wsgiref/handlers.py", line 255, in send_preamble
    ('Date: %s\r\n' % format_date_time(time.time())).encode('iso-8859-1')
  File "/usr/lib64/python3.4/wsgiref/handlers.py", line 453, in _write
    self.stdout.write(data)
  File "/usr/lib64/python3.4/socket.py", line 394, in write
    return self._sock.send(b)
BrokenPipeError: [Errno 32] Broken pipe
----------------------------------------
Exception happened during processing of request from ('127.0.0.1', 49020)
Traceback (most recent call last):
  File "/usr/lib64/python3.4/wsgiref/handlers.py", line 138, in run
    self.finish_response()
  File "/home/kwpolska/virtualenvs/nikola-py3/lib/python3.4/site-packages/ws4py/server/wsgirefserver.py", line 71, in finish_response
    SimpleHandler.finish_response(self)
  File "/usr/lib64/python3.4/wsgiref/handlers.py", line 180, in finish_response
    self.write(data)
  File "/usr/lib64/python3.4/wsgiref/handlers.py", line 274, in write
    self.send_headers()
  File "/usr/lib64/python3.4/wsgiref/handlers.py", line 332, in send_headers
    self.send_preamble()
  File "/usr/lib64/python3.4/wsgiref/handlers.py", line 255, in send_preamble
    ('Date: %s\r\n' % format_date_time(time.time())).encode('iso-8859-1')
  File "/usr/lib64/python3.4/wsgiref/handlers.py", line 453, in _write
    self.stdout.write(data)
  File "/usr/lib64/python3.4/socket.py", line 394, in write
    return self._sock.send(b)
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib64/python3.4/socketserver.py", line 305, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/lib64/python3.4/socketserver.py", line 331, in process_request
    self.finish_request(request, client_address)
  File "/usr/lib64/python3.4/socketserver.py", line 344, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib64/python3.4/socketserver.py", line 673, in __init__
    self.handle()
  File "/home/kwpolska/virtualenvs/nikola-py3/lib/python3.4/site-packages/ws4py/server/wsgirefserver.py", line 95, in handle
    handler.run(self.server.get_app())
  File "/usr/lib64/python3.4/wsgiref/handlers.py", line 141, in run
    self.handle_error()
  File "/usr/lib64/python3.4/wsgiref/handlers.py", line 368, in handle_error
    self.finish_response()
  File "/home/kwpolska/virtualenvs/nikola-py3/lib/python3.4/site-packages/ws4py/server/wsgirefserver.py", line 71, in finish_response
    SimpleHandler.finish_response(self)
  File "/usr/lib64/python3.4/wsgiref/handlers.py", line 180, in finish_response
    self.write(data)
  File "/usr/lib64/python3.4/wsgiref/handlers.py", line 274, in write
    self.send_headers()
  File "/usr/lib64/python3.4/wsgiref/handlers.py", line 331, in send_headers
    if not self.origin_server or self.client_is_modern():
  File "/usr/lib64/python3.4/wsgiref/handlers.py", line 344, in client_is_modern
    return self.environ['SERVER_PROTOCOL'].upper() != 'HTTP/0.9'
TypeError: 'NoneType' object is not subscriptable
----------------------------------------
[2015-07-31T07:20:50Z] INFO: ws4py: Terminating websocket [Local => 127.0.0.1:8000 | Remote => 127.0.0.1:49015]
[2015-07-31T07:20:50Z] INFO: ws4py: Managing websocket [Local => 127.0.0.1:8000 | Remote => 127.0.0.1:49030]
[2015-07-31T07:20:50Z] INFO: auto: <--- {'snipver': 1, 'protocols': ['http://livereload.com/protocols/official-6', 'http://livereload.com/protocols/official-7'], 'command': 'hello', 'ver': '2.2.1'}
[2015-07-31T07:20:50Z] INFO: auto: ---> {"protocols": ["http://livereload.com/protocols/official-7"], "command": "hello", "serverName": "nikola-livereload"}
[2015-07-31T07:20:51Z] INFO: auto: <--- {'command': 'info', 'plugins': {'less': {'disable': False, 'version': '1.0'}}, 'url': 'http://localhost:8000/'}
[2015-07-31T07:20:51Z] INFO: auto: ****** Browser connected: http://localhost:8000/
[2015-07-31T07:20:51Z] INFO: auto: ****** sending 0 pending messages
```

The error is probably caused by being unaware of browsers disconnecting, or the disconnect happening halfway through a reload request.  Though I think this is more of a ws4py bug and not our fault, especially since no Nikola code is mentioned by the traceback — so this should probably go upstream.

**Comment by ralsina** [comment] 2015-07-31 12:20
And after that, it seems to have reconnected, so it  should haveworked again. I'd say it's a ws4py bug and also that it doesn't seem to do anything.

**Comment by ralsina** [comment] 2015-09-09 22:03
I have been using auto a lot lately, and have not ran into any actual, visible errors, at least not "visible" in the sense of "my page stopped reloading" or "it failed" or "nikola crashed". So, closing.

**Closed by ralsina** 2015-09-09 22:03 UTC
Labels: bug, can't reproduce

**Comment by Kwpolska** [comment] 2015-09-10 15:40
I can’t find any G+ Comments docs anymore…

**Comment by ralsina** [comment] 2015-09-10 15:41
@Kwpolska wrong issue?

**Comment by Kwpolska** [comment] 2015-09-10 15:42
yeah, sorry. deleting all three comments.
