### ISSUE TITLE
navbar language links point to blogs instead of SITE_URL/lang/

### ISSUE THREAD

**Issue by smartass101** [getnikola/nikola#1008] opened 2014-01-28 10:14 UTC
I came across this issue while following the [Creating a Site (Not a Blog) with Nikola](http://getnikola.com/creating-a-site-not-a-blog-with-nikola.html) howto.

If I have in my config
```python
POSTS = [("posts/*.txt", "blog", "post.tmpl")]
PAGES = [("pages/*.txt", "", "story.tmpl")]
INDEX_PATH = "blog"
```
and create separate index.html + translations pages, all will work as advertized. 
However, when I click a language link on the navbar, it will take me to `SITE_URL/lang/blog/` (which may be empty) instead of the index.html translation. 
I tracked it down (in bootstrap3) to the `html_translations` function which uses the `${_link("index", None, langname)` path handler for those language navrbar links, which respects `INDEX_PATH`.

I don't think this is smart behavior, IMHO it is a bug. However, if anybody sees any benefit in such behavior, we should at least make it possible to disable it via some conf variable.

Looking forward to your opinions.

**Comment by e2jk** [comment] 2015-01-09 02:40
We already have a “site-wide index”, in the form of `SITE_URL`. That's where the upper-left link already links to anyway (without taking in effect the language, which is reported in #1573).

I notice that #1287 has been closed as a duplicate of this bug, but I would suggest unlinking these two issues as they're not real duplicates:
* #1008 could be fixed rather easily by having the translation links be hardcoded to point to `SITE_URL/lang/`
* and later work on fixing #1287 since that is a bit more complex as it involves handling non-translated links

Another reason to un-duplicate these 2 issues is that in my mind #1008 is a bug (you can't access the index page of a non-blog site in another language without manually fiddling with the URL in the browser) while #1287 is more of an enhancement (it would be *nicer* if you could stay on the same page when changing the language).

What do you think about first addressing this bug, and later the other enhancement (would require reopening #1287 so as to not forget about that problem)

**Closed** 2015-01-18 18:06 UTC
Labels: bug, PR exists
