### ISSUE TITLE
Creating .html files in the posts directory breaks the build process

### ISSUE THREAD

**Issue by ncouture** [getnikola/nikola#2506] opened 2016-09-22 22:30 UTC
This is related to #2505.

Steps to break the build process:
    - create a file ending with .html in the posts/ directory

```
$ nikola build
Scanning posts........done!
$ touch posts/a-file-to-break-build
(nikola-ncouture) self@bad:~/git/ncouture.github.io$ nikola build
Scanning posts........done!
(nikola-ncouture) self@bad:~/git/ncouture.github.io$ touch posts/a-file-to-break-build.html
(nikola-ncouture) self@bad:~/git/ncouture.github.io$ nikola build
Scanning posts...Traceback (most recent call last):
  File "/home/self/.virtualenvs/nikola-ncouture/lib/python3.4/site-packages/nikola/utils.py", line 871, in to_datetime
    value = dateutil.parser.parse(value)
  File "/home/self/.virtualenvs/nikola-ncouture/lib/python3.4/site-packages/dateutil/parser.py", line 1164, in parse
    return DEFAULTPARSER.parse(timestr, **kwargs)
  File "/home/self/.virtualenvs/nikola-ncouture/lib/python3.4/site-packages/dateutil/parser.py", line 558, in parse
    raise ValueError("String does not contain a date.")
ValueError: String does not contain a date.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/self/.virtualenvs/nikola-ncouture/lib/python3.4/site-packages/doit/doit_cmd.py", line 168, in run
    return command.parse_execute(args)
  File "/home/self/.virtualenvs/nikola-ncouture/lib/python3.4/site-packages/doit/cmd_base.py", line 122, in parse_execute
    return self.execute(params, args)
  File "/home/self/.virtualenvs/nikola-ncouture/lib/python3.4/site-packages/doit/cmd_base.py", line 380, in execute
    self, params, args)
  File "/home/self/.virtualenvs/nikola-ncouture/lib/python3.4/site-packages/nikola/__main__.py", line 279, in load_tasks
    self.nikola.gen_tasks('render_site', "Task", 'Group of tasks to render the site.'))
  File "/home/self/.virtualenvs/nikola-ncouture/lib/python3.4/site-packages/doit/loader.py", line 314, in generate_tasks
    for task_dict, x_doc in flat_generator(gen_result, gen_doc):
  File "/home/self/.virtualenvs/nikola-ncouture/lib/python3.4/site-packages/doit/loader.py", line 28, in flat_generator
    for item in gen:
  File "/home/self/.virtualenvs/nikola-ncouture/lib/python3.4/site-packages/nikola/nikola.py", line 1795, in gen_tasks
    for task in flatten(pluginInfo.plugin_object.gen_tasks()):
  File "/home/self/.virtualenvs/nikola-ncouture/lib/python3.4/site-packages/nikola/nikola.py", line 1789, in flatten
    for t in task:
  File "/home/self/.virtualenvs/nikola-ncouture/lib/python3.4/site-packages/nikola/plugins/task/tags.py", line 92, in gen_tasks
    self.site.scan_posts()
  File "/home/self/.virtualenvs/nikola-ncouture/lib/python3.4/site-packages/nikola/nikola.py", line 1894, in scan_posts
    timeline = p.plugin_object.scan()
  File "/home/self/.virtualenvs/nikola-ncouture/lib/python3.4/site-packages/nikola/plugins/misc/scan_posts.py", line 97, in scan
    self.site.get_compiler(base_path)
  File "/home/self/.virtualenvs/nikola-ncouture/lib/python3.4/site-packages/nikola/post.py", line 179, in __init__
    self.date = to_datetime(self.meta[self.default_lang]['date'], tzinfo)
  File "/home/self/.virtualenvs/nikola-ncouture/lib/python3.4/site-packages/nikola/utils.py", line 876, in to_datetime
    raise ValueError('Unrecognized date/time: {0!r}'.format(value))
ValueError: Unrecognized date/time: ''
```

My setup:
   - orgmode plugin
   - material-design theme

**Comment by stefanos82** [comment] 2016-09-22 23:13
Why did you use `touch` command and haven't used the standard nikola commands that come by default?

The standard way to create a new post or a new page is with `nikola new_post` inside your project directory.

Most probably the error happens due to missing `.meta` file that includes necessary information that nikola generates for you via the aforementioned command, but I could be wrong.

Also, what kind of files do you support? Does your `conf.py` includes the support for `.html` or not? That would be another indication towards your issue.

I would highly recommend to take a very brief look at the amazing [handbook](https://getnikola.com/handbook.html) Nikola offers to you with detailed information about how to configure your project.

I got bitten by missing arguments myself and advised  the handbook to resolve my issues.

Cheers.

**Comment by Kwpolska** [comment] 2016-09-23 06:29
@stefanos82 is right. In order to create a post, you should use `nikola new_post`, which will add the necessary metadata to the top of your created html file (or optionally a separate .meta file), unless you can write Nikola meta from memory.

That said, the error is a bit misleading (should tell you you're missing metadata, no idea why that didn't happen)

**Comment by ncouture** [comment] 2016-09-23 15:36
I've mostly been creating new posts without using the `nikola new_post` command and only creating .org files in posts/ and running my build process. Why is this ill-advised?

**Comment by Kwpolska** [comment] 2016-09-23 15:50
There is nothing preventing you from creating files manually. But if you do, you need to make sure your posts have the metadata they need. Nikola can sometimes guess the missing information, although it’s never perfect, so we don’t recommend relying on it.

**Comment by ralsina** [comment] 2016-09-24 22:47
This is not a bug, it's a broken input file missing metadata. Closing.

**Closed by ralsina** 2016-09-24 22:47 UTC
