### ISSUE TITLE
[BUG] Date in metadata can't be parsed using HTML post

### ISSUE THREAD

**Issue by napjon** [getnikola/nikola#3008] opened 2018-04-04 19:07 UTC
### Environment (if reporting a bug)

**Python Version:** 3.6

**Nikola Version:** v7.8.14

**Operating System:** OS X

### Description:

It was 7.2 since I create last blog using Nikola website. I've been using it since 3 years now. But when I rebuild all of my posts, suddenly the HTML metadata can't parse date. I post using HTML, and always give prefix like meta example below for a particular html:

```
<!--
                    .. title: Aadhaar Data and Relational Databases
                    .. slug: Aadhaar-Data-and-Relational-Databases
                    .. date: 2014-08-28 07:01:28 UTC+07:00
                    .. tags: Data Science,Data Wrangling
                    .. link: 
                    .. description: 
                    .. type: text
                    -->
```

All the metadata parsed correctly, except date, which points today at 00:00. I checked with `conf.py` and still comment out. Is there any changes? I checked with all the issues and seems nothing similar.

**Comment by Kwpolska** [comment] 2018-04-05 15:16
I can’t reproduce after copy-pasting your header. (macOS 10.13/Python 3.6/Nikola v7.8.14)

![image](https://user-images.githubusercontent.com/327323/38374815-faf490e0-38f4-11e8-8dbb-c595264894bb.png)

**Comment by Kwpolska** [comment] 2018-04-10 17:24
Can we see the full `conf.py`, source `.html` file, and the paths you use?

**Comment by Kwpolska** [comment] 2018-04-25 20:17
Reproduced. Happens due to HTML metadata reading. The `<title>` triggers the html metadata reader, but since you don’t have a date there, it fails.

```html
<!--
.. title: WTF
.. slug: wtf
.. date: 2014-08-28 07:01:28 UTC+07:00
-->
<title>Foo a Bar</title>
```

This should be fixed by making the HTML meta reader a best-effort thing and still look for comments. Needs a minor refactoring, and perhaps an API change (which we can do for v8).

**Closed** 2018-04-26 00:16 UTC
Labels: BLOCKER, bug

**Comment by napjon** [comment] 2018-04-26 06:07
@Kwpolska : Sorry for not getting back to you sooner. Thank you for looking and solving the issue. I'll check from my end.
