### ISSUE TITLE
Link behaviour when using sections

### ISSUE THREAD

**Issue by gkabbe** [getnikola/nikola#2731] opened 2017-04-20 09:30 UTC
### Environment (if reporting a bug)

**Python Version:**
3.5.3
**Nikola Version:**
7.8.4

**Operating System:**
Debian Jessie

### Description:

If I create two sections in a new Nikola project and add a post to each section, each post will contain a link to the other post, even though they are in two different sections.

Is it possible to change this behaviour, so that there are only links to posts in the same section?

**Comment by Kwpolska** [comment] 2017-04-20 13:24
Duplicate of #2625. There’s a plugin for that: `nikola plugin -i section_prevnext`, [see README](http://plugins.getnikola.com/v7/section_prevnext/).

**Closed by Kwpolska** 2017-04-20 13:24 UTC
Labels: duplicate
