### ISSUE TITLE
KaTeX doesn't render some equations

### ISSUE THREAD

**Issue by jco2** [getnikola/nikola#2888] opened 2017-08-14 21:05 UTC
A few people had issues with the built-in support for KaTeX: it can't render, for instance, `aligned` blocks, which is supported by KaTeX. With the help of @cqql, who wrote a special template for this, I could fix this problem. I'm a bit confused with this though...

I think the issue comes from the fact that in my html files the equations are not contained in `<div class="math"></div>` blocks... I can provide @cqql's template to help, with his permission.

**Comment by cqql** [comment] 2017-08-14 22:43
Yes, it is fine. I cannot remember why exactly, but for some reason the `USE_KATEX` setting did not work for me and I ended up integrating KaTeX manually by modifying one of the standard templates as follows.

```jinja2
{# -*- mode: jinja2 -*- #}

{% macro stylesheets() %}
  <link rel="stylesheet" href="/assets/katex/katex.min.css">
{% endmacro %}

{% macro scripts() %}
  <script src="/assets/katex/katex.min.js"></script>
  <script src="/assets/katex/contrib/auto-render.min.js"></script>
  <script>
    renderMathInElement(document.body, {delimiters: [
      {left: "\\begin{equation*}", right: "\\end{equation*}", display: true},
      {left: "\\[", right: "\\]", display: true},
      {left: "\\(", right: "\\)", display: false},
      {left: "$latex ", right: "$", display: false}
    ]});
  </script>
{% endmacro %}
```

**Comment by Kwpolska** [comment] 2017-08-15 06:03
This is caused by default KaTeX configuration. reST renders display math
using TeX equation* blocks. You can change it by setting KATEX_AUTO_RENDER
to a JS fragment (see docs).

Perhaps we should change the default config to include those blocks to
auto-render, or do so with div class="math".
-- 
Chris Warrick <https://chriswarrick.com/>

On Aug 15, 2017 00:43, "Marten Lienen" <notifications@github.com> wrote:

Yes, it is fine. I cannot remember why exactly, but for some reason the
USE_KATEX setting did not work for me and I ended up integrating KaTeX
manually by modifying one of the standard templates as follows.

{# -*- mode: jinja2 -*- #}

{% macro stylesheets() %}
  <link rel="stylesheet" href="/assets/katex/katex.min.css">
{% endmacro %}

{% macro scripts() %}
  <script src="/assets/katex/katex.min.js"></script>
  <script src="/assets/katex/contrib/auto-render.min.js"></script>
  <script>
    renderMathInElement(document.body, {delimiters: [
      {left: "\\begin{equation*}", right: "\\end{equation*}", display: true},
      {left: "\\[", right: "\\]", display: true},
      {left: "\\(", right: "\\)", display: false},
      {left: "$latex ", right: "$", display: false}
    ]});
  </script>
{% endmacro %}

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/getnikola/nikola/issues/2888#issuecomment-322330077>,
or mute the thread

**Comment by ralsina** [comment] 2018-02-16 16:10
So, not a bug?

**Comment by ralsina** [comment] 2018-03-06 19:02
So, I spent a little time looking.

Currently, the output of reSt's math directive doesn't work with KaTeX because it generates an equation environment and that is not supported:

```
d.innerHTML
"
\begin{equation*}
\int \frac{dx}{1+ax}=\frac{1}{a}\ln(1+ax)+C
\end{equation*}
"
katex.renderToString(d.innerHTML)
katex.min.js:1 Uncaught Error: KaTeX parse error: No such environment: equation* at position 8: 
\begin{̲e̲q̲u̲a̲t̲i̲o̲n̲*̲}̲
\int \frac{dx}…
    at new a (katex.min.js:1)
    at h.parseImplicitGroup (katex.min.js:1)
    at h.parseAtom (katex.min.js:1)
    at h.parseExpression (katex.min.js:1)
    at h.parseInput (katex.min.js:1)
    at h.parse (katex.min.js:1)
    at i (katex.min.js:4)
    at Object.u [as renderToString] (katex.min.js:1)
    at <anonymous>:1:7
```

So, just set KATEX_AUTORENDER as suggested in the docs and use \[yourquationhere\] if you want to use KaTeX.

Closing, but I am not an expert, so if I missed something, please reopen.

**Closed by ralsina** 2018-03-06 19:02 UTC

**Comment by Kwpolska** [comment] 2018-03-06 19:04
What if you added `\begin{equation*}` and `\end{equation*}` as delimiters to config? Would that fix anything?

**Comment by ralsina** [comment] 2018-03-06 19:09
Doesn't seem to do anything.

**Comment by cqql** [comment] 2018-03-07 10:41
Setting `KATEX_AUTO_RENDER` to
```
delimiters: [
  {left: "\\begin{equation*}", right: "\\end{equation*}", display: true},
  {left: "\\[", right: "\\]", display: true},
  {left: "\\(", right: "\\)", display: false},
  {left: "$latex ", right: "$", display: false}
]
```
might work similar to what I have done in my theme. Though maybe it did not because there must have been some reason for me to create my own theme for this change.

**Comment by Kwpolska** [comment] 2018-03-07 20:38
I got it to work as well. Fixed on master.
