### ISSUE TITLE
Base theme: mako error

### ISSUE THREAD

**Issue by Vd86xkht** [getnikola/nikola#3346] opened 2020-01-31 19:55 UTC
### Environment

**Python Version:**
3.7.3

**Nikola Version:**
8.0.3

**Operating System:**
Linux/Windows

### Description:
Following the steps in this theme tutorial [https://getnikola.com/creating-a-theme.html]() and after running `nikola build`. I get the following error:

`
[2020-01-31T19:13:55Z] ERROR: Nikola: Error loading tasks. An unhandled exception occurred.
[2020-01-31T19:13:55Z] ERROR: Nikola: mako.exceptions.CompileException: Named block 'extra_header' not allowed inside of def 'html_header' in file '/home/marcus/.local/lib/python3.7/site-packages/nikola/data/themes/base/templates/base_header.tmpl' at line: 16 char: 5
`

**Comment by Kwpolska** [comment] 2020-02-01 13:12
Duplicate of #3319, fix is on master (see that issue for details), but there hasn’t been a release since then.

**Closed by Kwpolska** 2020-02-01 13:12 UTC
Labels: bug, duplicate
