### ISSUE TITLE
Nikola depends on doit auto, which was removed from pydoit in 0.36

### ISSUE THREAD

**Issue by JesperDramsch** [getnikola/nikola#3615] opened 2022-04-23 12:08 UTC
### Environment

**Python Version:**
3.10
**Nikola Version:**
8.20
**Operating System:**
Windows / Docker with Ubuntu
### Description:

My nikola action is failing, but this will be true for every new installation of nikola.

This currently leads the `Nikola[extras]` installation to fail its build with:

     Traceback (most recent call last):
      File "/usr/local/bin/nikola", line 5, in <module>
        from nikola.__main__ import main
      File "/usr/local/lib/python3.10/site-packages/nikola/__main__.py", line 39, in <module>
        from doit.cmd_auto import Auto as DoitAuto
    ModuleNotFoundError: No module named 'doit.cmd_auto'

### Cause

Doit removed the "auto" package from the core pydoit.

See
- https://github.com/pydoit/doit/commit/5e1c695902626ca68236115da4fb827d0097e4f4
- https://github.com/pydoit/doit/issues/424
- https://github.com/pydoit/doit-auto1

### Possible Solutions

Temporarily it might be enough to pin 0.35 or some release before, in the long run monitor the release of `pydoit auto` and hope it just transitions out of the box?

**Comment by Kwpolska** [comment] 2022-04-23 12:09
Duplicate of #3612 and #3614, a new release with a fix will come out later today.

**Closed by Kwpolska** 2022-04-23 12:09 UTC
Labels: bug

**Comment by JesperDramsch** [comment] 2022-04-23 12:11
Sorry about that. Wasn't used to look for pinned issues like that.

**Comment by Kwpolska** [comment] 2022-04-23 12:12
(Please look for duplicates before reporting issues, whether they’re pinned or just closed.)

**Comment by JesperDramsch** [comment] 2022-04-23 12:23
(I did just say in that comment that I looked for duplicates but didn't see it and apologized.)

**Comment by Kwpolska** [comment] 2022-04-23 15:54
Nikola v8.2.1 is out with a fix for this issue.
