### ISSUE TITLE
image galery resize mismatch between width and length

### ISSUE THREAD

**Issue by ouzlou** [getnikola/nikola#3239] opened 2019-02-26 23:02 UTC
### Environment

**Python Version:**
3.5.3
**Nikola Version:**
8.0.2
**Operating System:**
debian 9.8
### Description:
an images oriented in portrait (1080x1620) are resized to (720x1080) despite of MAX_IMAGE_SIZE=1620

### solution :
file: lib/python3.5/site-packages/nikola/image_processing.py

line 106
`        size = w, h = im.size`
replaced by
`        w, h = im.size`
`        size = max(w,h), max(w,h)`

the 'if' in line 107 reset 'size' with a pair of equal values if resize is needed
but in case of no resize needed 'size' keeps the 2 different original values and there is maybe a mismatch between exif orientation and the actual

**Comment by ralsina** [comment] 2019-08-07 12:48
```
$ file galleries/1080_1620.png                                                                                                       (3s 357ms)  
galleries/1080_1620.png: PNG image data, 1080 x 1620, 8-bit/color RGB, non-interlaced
$ file output/galleries/1080_1620.png 
output/galleries/1080_1620.png: PNG image data, 1080 x 1620, 8-bit/color RGB, non-interlaced
$ grep MAX_IM conf.py 
MAX_IMAGE_SIZE = 1620
```

Can't reproduce with current master, closing.

**Closed by ralsina** 2019-08-07 12:48 UTC
Labels: bug
