### ISSUE TITLE
Iterative build does not work when using SHOW_UNTRANSLATED_POSTS

### ISSUE THREAD

**Issue by matclab** [getnikola/nikola#3112] opened 2018-07-05 08:32 UTC
### Environment (if reporting a bug)

**Python Version:** Python 3.6.5

**Nikola Version:** Nikola v8.0.0b2

**Operating System:** Linux 4.17.3-1-ARCH #1 SMP PREEMPT Tue Jun 26 04:42:36 UTC 2018 x86_64 GNU/Linux

### Description:
`nikola build` rebuild the output when a markdown post has changed, but the change does not appear in the output. The stdout shows that the corresponding html is being rebuild, but the output content does not change (verified by having the same md5sum on the input and on the output).

`nikola clean; nikola build` works as expected.

### Further analysis

It should be configuration dependant, because I failed to reproduce it when creating a new test site from scratch.

More testing shows that `SHOW_UNTRANSLATED_POSTS` may be the culprit, as shown by this little script reproducing the problem:

```shell
nikola init -q test$$
cd test$$
sed -i -e 's/# "es": ".\/es",/"fr": ".\/fr",/' \
   -e 's/# \(SHOW_UNTRANSLATED_POSTS\)/\1/' conf.py
nikola new_post -f markdown -t "Test post"
mv posts/test-post.md posts/test-post.fr.md
nikola build
md5sum posts/test-post.fr.md
md5sum output/posts/test-post/index.html
echo "OOOO" >> posts/test-post.fr.md
nikola build
md5sum posts/test-post.fr.md
md5sum output/posts/test-post/index.html
```
The output mds5sum does not differ where it should have.

**Comment by matclab** [comment] 2018-07-05 08:38
For completeness, here follows the test script output:
```
[2018-07-05T08:37:19Z] INFO: init: Created empty site at test13465.
Scanning posts........done!
[2018-07-05T08:37:20Z] INFO: new_post: Your post's text is at: posts/test-post.md
Creating New Post
-----------------

Title: Test post
Scanning posts........done!
.  render_taxonomies:output/archive.html
.  render_taxonomies:output/categories/index.html
.  render_taxonomies:output/fr/archive.html
.  render_taxonomies:output/fr/categories/index.html
.  render_posts:timeline_changes
.  render_posts:cache/posts/test-post.html
.  render_posts:cache/posts/test-post.fr.html
.  render_listings:output/listings/index.html
.  render_galleries:output/fr/galleries
.  render_galleries:output/galleries/index.html
.  render_galleries:output/galleries/rss.xml
.  render_galleries:output/fr/galleries/index.html
.  render_galleries:output/fr/galleries/rss.xml
.  copy_assets:output/assets/css/bootblog.css
.  copy_assets:output/assets/js/bootstrap.min.js
.  copy_assets:output/assets/js/popper.min.js
.  copy_assets:output/assets/js/jquery.min.js
.  copy_assets:output/assets/css/bootstrap.min.css
.  copy_assets:output/assets/css/theme.css
.  copy_assets:output/assets/js/gallery.min.js
.  copy_assets:output/assets/js/moment-with-locales.min.js
.  copy_assets:output/assets/js/baguetteBox.min.js
.  copy_assets:output/assets/js/gallery.js
.  copy_assets:output/assets/js/justified-layout.min.js
.  copy_assets:output/assets/js/html5shiv-printshiv.min.js
.  copy_assets:output/assets/js/fancydates.js
.  copy_assets:output/assets/js/html5.js
.  copy_assets:output/assets/js/fancydates.min.js
.  copy_assets:output/assets/xml/rss.xsl
.  copy_assets:output/assets/xml/atom.xsl
.  copy_assets:output/assets/css/nikola_ipython.css
.  copy_assets:output/assets/css/html4css1.css
.  copy_assets:output/assets/css/rst.css
.  copy_assets:output/assets/css/rst_base.css
.  copy_assets:output/assets/css/baguetteBox.min.css
.  copy_assets:output/assets/css/ipython.min.css
.  copy_assets:output/assets/css/nikola_rst.css
.  copy_assets:output/assets/css/code.css
.  render_sources:output/posts/test-post/index.md
.  render_sources:output/fr/posts/test-post/index.md
.  render_taxonomies:output/index.html
.  render_taxonomies:output/2018/index.html
.  render_taxonomies:output/fr/index.html
.  render_taxonomies:output/fr/2018/index.html
.  render_taxonomies:output/fr/rss.xml
.  render_pages:output/fr/posts/test-post/index.html
.  render_taxonomies:output/rss.xml
.  render_pages:output/posts/test-post/index.html
.  create_bundles:output/assets/css/all-nocdn.css
.  create_bundles:output/assets/css/all.css
.  create_bundles:output/assets/js/all-nocdn.js
.  create_bundles:output/assets/js/all.js
.  sitemap:output/sitemap.xml
.  sitemap:output/sitemapindex.xml
.  robots_file:output/robots.txt
6752ffb95e5becfc79798354bb3a2ec9  posts/test-post.fr.md
bfd8fb2d9256e28e436adb5c9beb0f65  output/posts/test-post/index.html
Scanning posts........done!
.  render_galleries:output/galleries
.  render_sources:output/posts/test-post/index.md
.  render_sources:output/fr/posts/test-post/index.md
.  render_posts:timeline_changes
.  render_taxonomies:output/index.html
.  render_taxonomies:output/fr/index.html
.  render_taxonomies:output/2018/index.html
.  render_taxonomies:output/fr/2018/index.html
.  render_taxonomies:output/rss.xml
.  render_pages:output/fr/posts/test-post/index.html
.  render_pages:output/posts/test-post/index.html
.  render_taxonomies:output/fr/rss.xml
.  sitemap:output/sitemap.xml
41436a785a3a24c815c340ebf134ace0  posts/test-post.fr.md
bfd8fb2d9256e28e436adb5c9beb0f65  output/posts/test-post/index.html
```

**Comment by ralsina** [comment] 2018-07-05 12:29
Can you check what the actual difference is between those two files?

**Comment by matclab** [comment] 2018-07-05 12:46
Hmmm not sure what you expected, but:
```diff
--- /tmp/test-post.fr.md	2018-07-05 14:44:05.560164417 +0200
+++ posts/test-post.fr.md	2018-07-05 10:28:28.222556100 +0200
@@ -10,3 +10,4 @@
 -->
 
 Write your post here.
+OOOO
```

**Comment by ralsina** [comment] 2018-07-05 13:54
Either I am missing something, or this is not a bug.

Here is what your test script does:

* Create a new empty site
* Enable a french translation
* Set SHOW_UNTRANSLATED_POSTS to True
* Creates an empty post in french
* Build the site

At that point, build the site. The output in output/posts/test-post/index.html shows the empty post.

Then:

* Add new content in that post ("OOOOOO").
* Rebuild the site

At this point, yes, the output is different, because it now contains the new content.

* The build was incremental, it builds a lot less than the first one.
* The content shown is the current one, and is correct.

What exactly do you expect to be different?

**Comment by ralsina** [comment] 2018-07-05 14:02
Ah, I see, the problem is that the changed output is stale.

Sorry!

**Comment by ralsina** [comment] 2018-07-05 14:04
I guess the file dependencies for indexes are wrong and don't take the "real" source of the file into account.

**Comment by ralsina** [comment] 2018-07-05 14:09
So, this is handled by the taxonomy plugin, which seems to get it from ``post.deps(lang)`` ... looking...

**Comment by ralsina** [comment] 2018-07-05 14:11
Weird.

This seems correct.

```
In [3]: site.timeline[0].deps('en')
Out[3]: ['cache/posts/foo.es.html', 'posts/foo.es.rst']
```

This is just lazy

```
In [4]: site.timeline[0].deps('es')
Out[4]:
['cache/posts/foo.es.html',
 'cache/posts/foo.es.html',
 'posts/foo.es.rst',
 'posts/foo.es.rst']
```

**Comment by ralsina** [comment] 2018-07-05 14:16
Ok, the problem is not actually with the indexes but with the HTML fragments.

* The english index and so on ARE rebuilt correctly. BUT
* They use cache/posts/foo.html which is not marked as dirty when you modify posts/foo.es.rst

So, that's it, this has probably been there since nikola 2 or so :-)

**Comment by ralsina** [comment] 2018-07-05 14:20
post.fragment_deps seems to be deeply broken:

```
In [6]: site.timeline[0].fragment_deps('en')
Out[6]: []

In [7]: site.timeline[0].fragment_deps('es')
Out[7]: []
```

**Comment by ralsina** [comment] 2018-07-05 16:51
PR with the one-line fix is at #3113

**Closed** 2018-07-05 18:52 UTC
Labels: BLOCKER, brown paper bag, bug

**Comment by matclab** [comment] 2018-07-06 07:12
Whow. That was fast !

Thank you.

**Comment by ralsina** [comment] 2018-07-06 12:51
@matclab you are welcome. Thanks for finding the bug in the first place!
