### ISSUE TITLE
Feature Request: nikola init should generate blog + static website

### ISSUE THREAD

**Issue by jonasstein** [getnikola/nikola#3251] opened 2019-04-14 15:39 UTC
I just advertised nikola at the python barcamp 2019 in germany. In the discussion we found out, that 
it is an FAQ how to modify nikola for a static website. 
It would help many users, if the (very nice) init tool could generate a combined static website with blog, or alternatively new commands like

```
nikola initstatic
nikola initblog
nikola initstaticblog
```

**Comment by encarsia** [comment] 2019-04-16 15:47
Hi,

I don't really understand why you need different initiation commands for this because what you put as 'static' (non blog-related) or blog content just depends on where you create it (posts/pages). And the rest is a little conf.py tweaking which you have to do anyway.

Regards,

**Comment by Kwpolska** [comment] 2019-04-16 16:28
This is a duplicate of issue #1760. If anyone wants to implement this feature, probably as a switch to `init` and not new commands, go ahead!

At the same time, I’ll close this issue, please continue discussion in #1760.

**Closed by Kwpolska** 2019-04-16 16:28 UTC
Labels: duplicate
