### ISSUE TITLE
Nikola crashing after successful deployment

### ISSUE THREAD

**Issue by kayhayen** [getnikola/nikola#3500] opened 2021-01-11 10:07 UTC
This is from my pipenv lock file, I checked, there is no update.

```
        "nikola": {
            "hashes": [
                "sha256:26f4fb1a2b0105cf0f71187c6c1eb54283767a883d1c8f4ca8c8039033217d27",
                "sha256:78f4e9dc233a75e10e575b8909b6aa212a11a6bfd534e86ec66befc4c53e7579"
            ],
            "index": "pypi",
            "version": "==8.1.2"
        },
```

Nikola is running in my CI on WSL Linux. I am executing `nikola deploy` with this `conf.py` snippet for it.

```
DEPLOY_COMMANDS = {
    "default" : [
        "rsync -ravz --exclude=.git --chown www-data:git --chmod Dg+x output/ censored@nuitka.net:/censored"
    ]
}
```

### Environment

**Python Version:**

This is 3.7

**Nikola Version:**

8.1.2

**Operating System:**

Linux WSL under Buildbot slave.

### Description:

Crash is this:

```
[2021-01-11 09:21:13] INFO: deploy: => preset 'default'
[2021-01-11 09:21:13] INFO: deploy: ==> rsync -ravz --exclude=.git --chown www-data:git --chmod Dg+x output/

... rsync output removed

[2021-01-11 09:21:14] INFO: deploy: Successful deployment
Traceback (most recent call last):
  File "/home/nuitka-buildslave/.local/share/virtualenvs/build-W1Z6Nt1u/lib/python3.7/site-packages/doit/doit_cmd.py", line 190, in run
    return command.parse_execute(args)
  File "/home/nuitka-buildslave/.local/share/virtualenvs/build-W1Z6Nt1u/lib/python3.7/site-packages/doit/cmd_base.py", line 150, in parse_execute
    return self.execute(params, args)
  File "/home/nuitka-buildslave/.local/share/virtualenvs/build-W1Z6Nt1u/lib/python3.7/site-packages/nikola/plugin_categories.py", line 145, in execute
    return self._execute(options, args)
  File "/home/nuitka-buildslave/.local/share/virtualenvs/build-W1Z6Nt1u/lib/python3.7/site-packages/nikola/plugins/command/deploy.py", line 99, in _execute
    self._emit_deploy_event(last_deploy, new_deploy, clean, undeployed_posts)
UnboundLocalError: local variable 'clean' referenced before assignment
```

Seems like something that PyLint didn't find?

Yours,
Kay

**Comment by Kwpolska** [comment] 2021-01-11 19:23
Duplicate of #3479, already fixed in master.

**Closed by Kwpolska** 2021-01-11 19:23 UTC
Labels: bug, duplicate
