### ISSUE TITLE
zsh tabcompletion not working

### ISSUE THREAD

**Issue by lecovi** [getnikola/nikola#1870] opened 2015-07-07 19:52 UTC
I'm using `Nikola v.7.6.0` and trying to get zsh tabcompletion...

When I do source to the `_nikola_zsh` I get an error on: 
```
_nikola_zsh:447: unmatched ' 
```

I've found one error on line 232 at **`import wordpress`**
```
            '(-d|--no-drafts)'{-d,--no-drafts}'[Don't import drafts]' \
```
The **'** of *"Don't"* is not escaped.

Removing this, brings me a new one:
```
_arguments:comparguments:312: can only be called from completion function
```

Thanks in advance!

**Comment by Kwpolska** [comment] 2015-07-08 07:15
Hello,
thank you for the report, but this should be filed in doit instead, which is responsible for the tab completion (and about 90% of Nikola’s awesomeness).

The first issue can be fixed by using `"` for strings and escaping `\"` if needed.  I opened a pull request in doit, pydoit/doit#72, that should fix the issue (and that produces correct files).

The second error is probably caused by misuse of the completion.  The completion files are not supposed to be sourced directly, instead you must put it in a directory in `$fpath`.  See `echo $fpath` to get the list, use `fpath=(/path/to/directory/with/your/nikola/completions $fpath)` in `.zshrc` to change it if you don’t have any good place to throw it into.

**Closed** 2015-07-08 09:55 UTC
Labels: someone else's bug, user error
