### ISSUE TITLE
Nikola 'clean' command shows an error and fails on Python 3

### ISSUE THREAD

**Issue by amireldor** [getnikola/nikola#3004] opened 2018-03-30 23:18 UTC
**Python Version:**
```
$ python --version
Python 3.6.3
```

**Nikola Version:**
```
$ nikola version
Nikola v7.8.13
```

**Operating System:**
MacOS High Sierra 10.13.3
:'-(

### Description:

I'm trying to clean my site from old now-empty categories, dead pages, etc. I get this error with `nikola clean`. I am test-driving Nikola, it's a fresh pip install (both with and without [Extras]).

Actually, I switched to my Python 3 env after seeing a deprecation warning when using Python 2. In Python 2, this error in the nikola clean command _did not occur_.

```
$ nikola clean
Scanning posts........done!
Traceback (most recent call last):
  File "/Users/shmu/.virtualenvs/nikola/lib/python3.6/site-packages/doit/doit_cmd.py", line 177, in run
    return command.parse_execute(args)
  File "/Users/shmu/.virtualenvs/nikola/lib/python3.6/site-packages/doit/cmd_base.py", line 127, in parse_execute
    return self.execute(params, args)
  File "/Users/shmu/.virtualenvs/nikola/lib/python3.6/site-packages/doit/cmd_base.py", line 420, in execute
    return self._execute(**exec_params)
  File "/Users/shmu/.virtualenvs/nikola/lib/python3.6/site-packages/doit/cmd_clean.py", line 109, in _execute
    self.clean_tasks(to_clean, dryrun, cleanforget)
TypeError: clean_tasks() takes 3 positional arguments but 4 were given
(nikola)

```

**Comment by Kwpolska** [comment] 2018-03-31 08:49
We forgot to backport a fix for this issue from our v8 branch. A new v7.8.14 release will be out shortly.

This problem did not occur on Python 2, because Python 2 is limited to an older version of doit (0.29.0), and the issue is caused by an API change in v0.31.0. With the patch, both Pythons and both doit versions will work properly.

**Comment by Kwpolska** [comment] 2018-03-31 09:37
v7.8.14 is out [on PyPI](https://pypi.org/project/Nikola/7.8.14/).

**Closed by Kwpolska** 2018-03-31 09:37 UTC
Labels: bug
