### ISSUE TITLE
How to avoid duplicated ids and h1 on the blog index ?

### ISSUE THREAD

**Issue by wichtounet** [getnikola/nikola#2570] opened 2016-11-27 17:49 UTC
Hi, 

I was trying to optimize my site to fix some issues in HTML and I found out that there were issues on the blog index page because of the duplicated h1 and duplicate id (the ids automatically generated by Nikola on the headers for instance). 

Is there anyway to fix this ?

Thanks

**Comment by Kwpolska** [comment] 2016-11-27 17:50
Please elaborate. Do you mean that when there are headers in your blog posts, and those have IDs, the IDs are duplicated?

Well, that would be pretty hard to fix, if even doable.

**Comment by wichtounet** [comment] 2016-11-27 17:51
@Kwpolska I edited my post. Sorry, I created it empty by error.

**Comment by Kwpolska** [comment] 2016-11-27 17:55
Please show a .html file that exhibits this problem.

**Comment by wichtounet** [comment] 2016-11-27 18:41
The index of my blog: http://baptiste-wicht.com/

There are several duplicated IDs. And several H1 which is not very good for SEO, but not an HTML error as far as I know.

**Comment by Kwpolska** [comment] 2016-11-27 19:22
Yeah, that’s what I was talking about. This is caused by posts having the same headers. This *could* be solved by post-processing the HTML, making a list of all IDs, finding duplicates and assigning new IDs to elements but careful enough not to create new duplicates. I’ll leave this open if anyone wants to fix this, but it’s a really minor bug of the *huge effort — small reward* category in my opinion.

> And several H1 which is not very good for SEO, but not an HTML error as far as I know.

[citation needed]. Nowadays <h1> can be duplicated just fine.

**Comment by wichtounet** [comment] 2016-11-28 06:47
Wouldn't it simply be possible to generate IDs that are unique directly ? Concatenating the ID of the article (if there is any in nikola) and the name of the header ? 

> [citation needed]. Nowadays <h1> can be duplicated just fine.

You're right, it seems it is not much of an issue currently.

**Comment by sukiletxe** [comment] 2016-11-28 11:56
Well, the slug could be used as an id. Or maybe the gid you use in 
feeds, although that wouldn't be applicable for pages.

**Comment by Kwpolska** [comment] 2016-11-28 16:50
There is no simple ID we could use that would (a) look good and (b) be guaranteed to have only characters allowed in id tags.

And Nikola doesn’t generate any of those itself, those come from reST (and possibly other input formats), so fixing this for reST only will only solve part of the problem.

**Comment by wichtounet** [comment] 2016-11-29 10:10
Alright, I would not have this problem to be so complicated to fix. I think I'll leave with this for now ;)

**Comment by ralsina** [comment] 2017-05-04 23:20
As usual, we *can* fix this in postprocessing (we already do extensive munching of the generated HTML). If you don't mind having really awful IDs it's not really very hard to do.

**Comment by Kwpolska** [comment] 2017-05-06 19:24
I think I can solve this with *nice* IDs, as long as I figure out a way to get all IDs on a page. (Performance might be awful.)

**Comment by Kwpolska** [comment] 2017-05-14 16:07
Implemented on `header-deduplication` branch. (#2743 must be merged first)

**Closed** 2017-05-21 09:56 UTC
Labels: bug, minor, PR exists

**Comment by wichtounet** [comment] 2017-05-22 07:54
Thanks a lot for all the work. I'll try this on the next release and let you know.

**Comment by wichtounet** [comment] 2017-05-30 07:56
I tried this on my blog and it works fine :)

Thanks a lot :)
