### ISSUE TITLE
Gallery URLs broken

### ISSUE THREAD

**Issue by ericcotelnu** [getnikola/nikola#2499] opened 2016-09-17 18:09 UTC
Hi,

dunno if it's my set up, or an actual bug, but the URLs in the img and a tags are missing a 'g' in galleries.

Some live example HTML source:

`<a href="/alleries/logo-benehsi.png" class="thumbnail image-reference" title="Logo benehsi">
              <img src="/alleries/logo-benehsi.thumbnail.png" alt="Logo benehsi"></a>`

Before and after I explicitly set GALLERY_PATHS, it's been doing this. I looked at the task/gallery.py file but due to my python noobishness I dunno where it's stripping that 'g'. I also wanted to implement a DEBUG logging facility to see where/what was doing this, and I've no real clue (I've googled and checked most of the docs on the web site).

Thanks, and apologies if this has already been dealt with before.

**Comment by Kwpolska** [comment] 2016-09-17 18:10
In what file does this happen? What is your URL_TYPE set to?

**Comment by ericcotelnu** [comment] 2016-09-17 18:20
URL_TYPE = 'full_path'

**Comment by Kwpolska** [comment] 2016-09-17 18:21
I still can’t reproduce with the demo site. Could you try creating a new demo site (`nikola init -qd nikolademo`), changing this setting and telling me if it happens there?

**Comment by ericcotelnu** [comment] 2016-09-17 18:23
I made a mistake (was reading old closed bug before), here's my config for GALLERY_FOLDERS

GALLERY_FOLDERS = {"galleries": "galleries"}

i.e., stock config setting.

Sure, gimme a few. Thanks.

**Comment by ericcotelnu** [comment] 2016-09-17 18:32
Works OK with rel_path, but absolute and full_path I still get a "/alleries/".

**Comment by Kwpolska** [comment] 2016-09-17 18:34
Cannot reproduce with Nikola v7.8.0 on macOS (I’m looking at `output/galleries/demo/index.html`). What OS are you on, and are you using an up-to-date version of Nikola?

**Comment by ericcotelnu** [comment] 2016-09-17 18:44
Yup, installed from pip3, on Linux, Debian.

`$ nikola --version`
`Nikola v7.8.0`

**Comment by ericcotelnu** [comment] 2016-09-17 18:58
OK, viewed the site with a non-text browser (was using w3m), and it's still borked, but 1) the images show up 2) I made a "test" sub-dir with the Nikola Tesla images from the demo site, and I still get the "/alleries/", and the usual 404 from such things :P.

mkdir nikolatesla/
cp images to there
build site
visit in gnome's browser
images show up, but 404 on /alleries/nikolatesla/ . Maybe python developed an allergy to me :P (play on words -- my silly sense of humour is kicking in, apologies =) ).

**Comment by Kwpolska** [comment] 2016-09-17 19:07
I’ve never seen behavior like this, and I don’t know what could cause this. I can’t reproduce on Debian 8.1 `pip3 uninstall Nikola; pip3 install -U Nikola`

**Comment by ericcotelnu** [comment] 2016-09-17 19:13
It is odd, first time I've seen this. I'll try re-installing it.

**Comment by ericcotelnu** [comment] 2016-09-17 19:21
No change. Is it safe to rm the .doit.db.db file ? (Yeah, it added an extra .db somewhere, I haven't changed it).

**Comment by ericcotelnu** [comment] 2016-09-17 19:24
relevant URL https://eric.malsum.org/galleries/ -- view source, scroll down, then take a look for yourself. The images show up but the A and IMG tags are wrong.

**Comment by ericcotelnu** [comment] 2016-09-17 19:35
Well, for now, Imma switch to rel_path for now since it works.

**Comment by Kwpolska** [comment] 2016-09-21 16:23
Because I can’t think of a way this could happen, could you please:

* create a clean virtualenv and install Nikola there? (follow the install process on [our website](https://getnikola.com/getting-started.html) if in doubt)
* try on a different computer (or virtual machine) running a similar OS version?

**Comment by ralsina** [comment] 2016-10-24 15:58
1 month gone, no ay to reproduce yet. Let's close it, if there is new info at some point, it can be reopened.

**Closed by ralsina** 2016-10-24 15:58 UTC
Labels: can't reproduce
