### ISSUE TITLE
Role :doc: is not aware of locale

### ISSUE THREAD

**Issue by Peibolvig** [getnikola/nikola#2112] opened 2015-09-22 22:50 UTC
Trying Nikola v7.7.1 demo site in local machine, with 3 locales (es, en, gl)

The role :doc: is not behaving as expected.
Take for example the one in line 23 of the posts/1.rst file, from the demo:

    * :doc:`See a demo listing <listings-demo>`

When I'm not in the default locale, for example 'en', the link is:

    http://localhost:8000/stories/listings-demo/

The expected link would be:

    http://localhost:8000/en/stories/listings-demo/

I thought this could be related to #1219 but I'm using the v7.7.1, which is the one with the fix for that issue.

I also tested creating listings-demo.en.rst file, but didn't work either.

The URL *http://localhost:8000/**en**/stories/listings-demo/*  does exist, so it seems a problem with the building of the link when using the :doc: role.
Using the translated version page link (with the 'en') seems good, so the building process for the page is ok.

**Comment by ralsina** [comment] 2015-09-23 12:49
Indeed that looks like a bug.

**Comment by ralsina** [comment] 2015-09-23 14:06
I can't reproduce this.

I created anempty site, then configured it for both spanish and english (english as default).

I created two posts, foo and bar, in both languages, fooo with a link to bar, and viceversa.
Copied both posts into spanish versions.

Built the site, and everything points to the right thing:

* foo in english -> bar in english
* foo in spanish -> bar in spanish
* bar in english -> foo in english
* bar in spanish -> foo in spanish

Could you try to create as small a test case as possible and send it to me?

**Comment by Kwpolska** [comment] 2015-09-23 15:06
On a side note, both the directive and the `link://` protocol should support specifying a language.

**Comment by ralsina** [comment] 2015-09-23 15:09
We could add a ?lang=xx thing that overrides the "current" language in ``link://`` ... not sure how that would work on the ``:doc:`` role, those things are not meant to have arguments.

**Comment by Peibolvig** [comment] 2015-09-23 22:29
Ok, here are the steps to reproduce and the tests I made for the issue.

Steps to reproduce
===============
Setting the site
-------------------
    nikola init --demo mydoctest
Let every default value but languages ---> en,es,gl

At this point, **posts** folder contains **1.rst**

    nikola build
    nikola serve

Testing different scenarios
----------------------------------
**FIRST TEST -- RESULT: KO**
*Test the links with only the file '1.rst',* **without lang renaming**
* Go to: http://localhost:8000
The link ![1](https://cloud.githubusercontent.com/assets/1297980/10059354/c87ae386-624a-11e5-8154-cd16c7ced97e.png) points to --> http://localhost:8000/stories/listings-demo/

* Now go to: http://localhost:8000/es/
The link ![1](https://cloud.githubusercontent.com/assets/1297980/10059354/c87ae386-624a-11e5-8154-cd16c7ced97e.png) points to --> http://localhost:8000/stories/listings-demo/
**Should be pointing to** --> http://localhost:8000/**es**/stories/listings-demo/
That link would have the same content because there is only one '1.rst' file.
The URL http://localhost:8000/**es**/stories/listings-demo/ actually does exist.

**SECOND TEST -- RESULT: KO**
*Test the links with only the file '1.rst',* **renamed to the default language** --> *'1.en.rst'*
* Go to: http://localhost:8000
The link ![1](https://cloud.githubusercontent.com/assets/1297980/10059354/c87ae386-624a-11e5-8154-cd16c7ced97e.png) points to --> http://localhost:8000/stories/listings-demo/

* Now go to: http://localhost:8000/es/
The link ![1](https://cloud.githubusercontent.com/assets/1297980/10059354/c87ae386-624a-11e5-8154-cd16c7ced97e.png) points to --> http://localhost:8000/stories/listings-demo/
**Should be pointing to** --> http://localhost:8000/**es**/stories/listings-demo/
That link would have the same content because there is only one '1.en.rst' file.
The URL http://localhost:8000/**es**/stories/listings-demo/ actually does exist.

**THIRD TEST -- RESULT: KO**
*Test the links with only the file '1.rst',* **renamed to one NON default language** --> *'1.es.rst'*
Same results as previous tests

**FOURTH TEST -- RESULT: KO**
*Test the links with one file for several languages but not all of them --> '1.en.rst', '1.es.rst'*
* Go to: http://localhost:8000
The link ![1](https://cloud.githubusercontent.com/assets/1297980/10059354/c87ae386-624a-11e5-8154-cd16c7ced97e.png) points to --> http://localhost:8000/stories/listings-demo/

* Now go to: http://localhost:8000/es/
The link ![1](https://cloud.githubusercontent.com/assets/1297980/10059354/c87ae386-624a-11e5-8154-cd16c7ced97e.png) **correctly** points to --> http://localhost:8000/**es**/stories/listings-demo/

* Now go to: http://localhost:8000/gl/
The link ![1](https://cloud.githubusercontent.com/assets/1297980/10059354/c87ae386-624a-11e5-8154-cd16c7ced97e.png) points to --> http://localhost:8000/stories/listings-demo/
**Should be pointing to** --> http://localhost:8000/**gl**/stories/listings-demo/
That link would have the same content because there is only one default language '1.en.rst' file.
The URL http://localhost:8000/**gl**/stories/listings-demo/ actually does exist.

**FIFTH TEST -- RESULT: OK**
*Test the links with one file for each language --> '1.en.rst', '1.es.rst', '1.gl.rst'*
* Go to: http://localhost:8000
The link ![1](https://cloud.githubusercontent.com/assets/1297980/10059354/c87ae386-624a-11e5-8154-cd16c7ced97e.png) points to --> http://localhost:8000/stories/listings-demo/

* Now go to: http://localhost:8000/es/
The link ![1](https://cloud.githubusercontent.com/assets/1297980/10059354/c87ae386-624a-11e5-8154-cd16c7ced97e.png) **correctly** points to --> http://localhost:8000/**es**/stories/listings-demo/

* Now go to: http://localhost:8000/gl/
The link ![1](https://cloud.githubusercontent.com/assets/1297980/10059354/c87ae386-624a-11e5-8154-cd16c7ced97e.png) **correctly** points to --> http://localhost:8000/**gl**/stories/listings-demo/

**This fifth way, is the only one that behaves as expected, in every case.**

To wrap up
--------------
If you have several languages configured, and you want to use the :doc: role, you are being forced to have 1 file for each post and language always. Even if you decide that one post will be in English only or whatever, you **must** have the same file with names: 1.en.rst, 1.es.rst, 1.gl.rst,...
If you don't do that, the user of the site can *magically* switch from one language to another without even notice, and needing to click on the desired language again when he goes to another section from the non-desired language link.

The output files for every language are generated even when a post only have one source file in one language, but not always used by :doc: role.

**Comment by ralsina** [comment] 2015-09-23 23:57
Test 1:

Hmmm... so you want the link to point to different, localized links even **without** actually creating a translation? I doubt that will ever happen. If you want different content in different languages, you **will** have to add a translated file, even if just by copying it.

Test 2:

Renaming a file from  1.rst to 1.en.rst when en is the default language doesn't do anything. This is exactly the same as test 1.

have not gotten around yet to follow tests 3 and 4.

**Comment by Kwpolska** [comment] 2016-02-11 13:06
I’m closing this, because this would require extra work and might result in some glitches that not everybody would want. If you don’t translate a post, it also makes sense that users are sent to the default language version — how would you feel if you were sent from an article written in English, residing in /es/, to another article written in Spanish, without actually speaking Spanish?

Then again, these are things everyone has their own opinion on.

**Closed by Kwpolska** 2016-02-11 13:06 UTC
Labels: bug
