### ISSUE TITLE
Build error for markdown post with footnotes

### ISSUE THREAD

**Issue by asmeurer** [getnikola/nikola#3363] opened 2020-04-01 04:49 UTC
My site at http://github.com/asmeurer/blog used to build, but it doesn't any more. It fails on the post tuples.markdown. Based on the traceback, I think it is because it is a Markdown post with footnotes (note that most of my other posts uses commonmark, but I have to use python-markdown for this post because commonmark doesn't support footnotes)

```
.  render_posts:cache/posts/tuples.html
TaskError - taskid:render_posts:cache/posts/tuples.html
PythonAction Error
Traceback (most recent call last):
  File "/Users/aaronmeurer/anaconda3/envs/blog-nikola-pip36/lib/python3.6/site-packages/doit/action.py", line 424, in execute
    returned_value = self.py_callable(*self.args, **kwargs)
  File "/Users/aaronmeurer/anaconda3/envs/blog-nikola-pip36/lib/python3.6/site-packages/nikola/post.py", line 641, in compile
    lang)
  File "/Users/aaronmeurer/anaconda3/envs/blog-nikola-pip36/lib/python3.6/site-packages/nikola/plugins/compile/markdown/__init__.py", line 122, in compile
    output, shortcode_deps = self.compile_string(data, source, is_two_file, post, lang)
  File "/Users/aaronmeurer/anaconda3/envs/blog-nikola-pip36/lib/python3.6/site-packages/nikola/plugins/compile/markdown/__init__.py", line 110, in compile_string
    output, _ = self.converters[lang].convert(new_data)
  File "/Users/aaronmeurer/anaconda3/envs/blog-nikola-pip36/lib/python3.6/site-packages/nikola/plugins/compile/markdown/__init__.py", line 56, in convert
    result = self.markdown.convert(data)
  File "/Users/aaronmeurer/anaconda3/envs/blog-nikola-pip36/lib/python3.6/site-packages/markdown/core.py", line 269, in convert
    newRoot = treeprocessor.run(root)
  File "/Users/aaronmeurer/anaconda3/envs/blog-nikola-pip36/lib/python3.6/site-packages/markdown/extensions/footnotes.py", line 388, in run
    footnotesDiv = self.footnotes.makeFootnotesDiv(root)
  File "/Users/aaronmeurer/anaconda3/envs/blog-nikola-pip36/lib/python3.6/site-packages/markdown/extensions/footnotes.py", line 181, in makeFootnotesDiv
    self.parser.parseChunk(surrogate_parent, self.footnotes[id])
  File "/Users/aaronmeurer/anaconda3/envs/blog-nikola-pip36/lib/python3.6/site-packages/markdown/blockparser.py", line 105, in parseChunk
    self.parseBlocks(parent, text.split('\n\n'))
  File "/Users/aaronmeurer/anaconda3/envs/blog-nikola-pip36/lib/python3.6/site-packages/markdown/blockparser.py", line 123, in parseBlocks
    if processor.run(parent, blocks) is not False:
  File "/Users/aaronmeurer/anaconda3/envs/blog-nikola-pip36/lib/python3.6/site-packages/markdown/blockprocessors.py", line 591, in run
    p = etree.SubElement(parent, 'p')
TypeError: SubElement() argument 1 must be xml.etree.ElementTree.Element, not Element
```

This happens with the latest version of Nikola (see the build on [Travis](https://travis-ci.org/github/asmeurer/blog)).

If you can suggest any workarounds, like a version I should downgrade to, that would be great. Right now I cannot build my site because of this.

**Comment by Kwpolska** [comment] 2020-04-01 11:38
This seems to be a conflict between Markdown and ipynb (ipynb modifies the markdown plugin, apparently).  Quick workaround: disable ipynb.  But this should probably be reported to the ipynb folks (with a minimum reproducible example).

**Comment by ralsina** [comment] 2020-04-01 11:44
Alternatively some of the other markdowns also support footnotes, like
misaka (but their syntax highlighting is strange) ... markdown is complex
sometimes.

**Comment by ashfinal** [comment] 2020-04-01 15:45
Seems like a bug in Markdown 3.2.1. Downgrading to Markdown 3.1.1 works for me.
Try this:
```shell
  - pip install Markdown==3.1.1
```

The full version can be found [here](https://github.com/macplay/macplay.github.io/blob/src/.travis.yml) .

**Comment by asmeurer** [comment] 2020-04-01 16:58
As an unrelated note, I discovered https://pypi.org/project/marko/. I haven't tried it yet, but if it really works like it says (commonmark syntax plus footnote support), it would be awesome to have support for it in Nikola.

**Comment by Kwpolska** [comment] 2020-04-01 17:03
> Seems like a bug in Markdown 3.2.1. Downgrading to Markdown 3.1.1 works for me.

Behavior *did* change in 3.2.x, but if you remove *.ipynb from POSTS, everything works.

> As an unrelated note, I discovered https://pypi.org/project/marko/. I haven't tried it yet, but if it really works like it says (commonmark syntax plus footnote support), it would be awesome to have support for it in Nikola.

You can try to write a plugin and contribute it to plugins.getnikola.com, it should be pretty easy to do.

**Comment by ralsina** [comment] 2020-04-01 17:03
Adding more markdown thingies is very easy (we have like 5?) I was planning
on adding https://myst-parser.readthedocs.io/en/latest/using/syntax.html which
is a reSt-flavored markdown.

**Comment by asmeurer** [comment] 2020-04-01 17:59
Thanks. I found that either downgrading Markdown or removing ipynb from my conf.py fixes the problem (I've done the latter since I don't actually have any notebook posts and I don't plan to have any).

**Comment by Kwpolska** [comment] 2020-04-01 18:05
We should still try to figure out what goes wrong and get it fixed, although this bug seems really weird from my initial testing.

**Comment by Kwpolska** [comment] 2020-04-01 22:51
I’ve been trying to debug this, and it’s really crazy.

This breaks:

```py
import markdown
#from defusedxml import cElementTree as ElementTree
from defusedxml import ElementTree

text = """Hello, world! [^fn]

[^fn]: I am a footnote."""

print(markdown.markdown(text, extensions=["footnotes"]))
```

But, if you import markdown *after* defusedxml, it works.  I’ll need to debug a little longer to figure out which project is responsible for this being broken: defusedxml for doing weird stuff to stdlib modules, jupyter/nbconvert being trigger-happy with random imports, or Markdown somehow mixing up ElementTrees (they had a bit of a refactor with them in 3.2).  Importing `defusedxml` if available before we load the markdown plugin is a possible solution, but not one I would prefer to implement.

---

If you’ve got a lot of Markdown posts, especially with extensions: please help out by trying to build all your posts with markdown==3.1.1, and again with markdown==3.2.1, and show posts that fail to build.

**Comment by ralsina** [comment] 2020-04-01 23:21
Uploaded a marko plugin to github right now. Not very tested but the
basics work.

I don't think their TOC extension supports using [TOC] in the document, so
it may not be very useful.

https://github.com/getnikola/plugins/tree/master/v8/marko

**Comment by asmeurer** [comment] 2020-04-01 23:35
defusedxml apparently can monkeypatch the standard library, so that might be related https://github.com/tiran/defusedxml

**Comment by asmeurer** [comment] 2020-04-01 23:41
In fact, the error message does suggest this is the problem. If defusedxml does something like

```
xml.ElementTree.Element = monkeypatched_ElementTree
```

and markdown does

```
from xml.ElementTree import Element
```

then if you import markdown first, Markdown will still have the old, non-monkeypatched version. And if the old non-monkeypatched and new monkeypatched classes mix, you might get an error message just like the one we see here where it says the class is the wrong type but it apparently is the right type.

The defusedxml docs don't make it clear if monkey patching is supposed to always happen. But if it does, then making sure it is imported first is indeed the correct solution. Markdown could also be patched to always use something like

```
xml.ElementTree.Element
```

so that it always uses the monkeypatched version once the monkeypatch happens.

**Comment by ralsina** [comment] 2020-04-14 08:55
So, @Kwpolska are you still interested on figuring this out? When you are not anymore let's close it, I am not sure there's much we can do.

**Comment by Kwpolska** [comment] 2020-04-14 16:12
I unassigned myself, but I’m not sure how to proceed this issue. The workaround is ugly, but I guess that would be the best approach for now. Perhaps we just should report it to `defusedxml` that their monkeypatching breaks stuff and leave it to them to fix it. The minimum reproducing example is:

```py
import markdown
from defusedxml import ElementTree

text = """Hello, world! [^fn]

[^fn]: I am a footnote."""

print(markdown.markdown(text, extensions=["footnotes"]))

**Comment by ralsina** [comment] 2020-04-14 16:20
If pinning markdown "fixes" it, it's a possibility, and report it to both markdown and defusedxml.

**Comment by bashtage** [comment] 2020-05-04 11:46
Importing

```
from defusedxml import ElementTree
```

in `conf.py` allows 3.2.1 to be used.

**Comment by ralsina** [comment] 2020-05-25 15:55
In general, I don't think this is really a Nikola issue. Closing.

**Closed by ralsina** 2020-05-25 15:55 UTC
Labels: bug, someone else's bug
