### ISSUE TITLE
Nikola 7.3.0 and Pyphen 0.9.1: nikola/post.py", line 947, in hyphenate results in KeyError: None

### ISSUE THREAD

**Issue by devurandom** [getnikola/nikola#1613] opened 2015-02-06 10:50 UTC
```
[…]
.  render_indexes:output/index.html
########################################
TaskError - taskid:render_indexes:output/index.html
PythonAction Error
Traceback (most recent call last):
  File "…/.local/lib/python3.4/site-packages/doit/action.py", line 372, in execute
    returned_value = self.py_callable(*self.args, **kwargs)
  File "…/.local/lib/python3.4/site-packages/nikola/nikola.py", line 898, in render_template
    template_name, None, local_context)
  File "…/.local/lib/python3.4/site-packages/nikola/plugins/template/mako.py", line 108, in render_template
    data = template.render_unicode(**context)
  File "…/.local/lib/python3.4/site-packages/mako/template.py", line 452, in render_unicode
    as_unicode=True)
  File "…/.local/lib/python3.4/site-packages/mako/runtime.py", line 803, in _render
    **_kwargs_for_callable(callable_, data))
  File "…/.local/lib/python3.4/site-packages/mako/runtime.py", line 835, in _render_context
    _exec_template(inherit, lclcontext, args=args, kwargs=kwargs)
  File "…/.local/lib/python3.4/site-packages/mako/runtime.py", line 860, in _exec_template
    callable_(context, *args, **kwargs)
  File "…/om/cache/.mako.tmp/base.tmpl.py", line 123, in render_body
    context['self'].content(**pageargs)
  File "…/om/cache/.mako.tmp/index.tmpl.py", line 95, in render_content
    __M_writer(str(post.text(teaser_only=True)))
  File "…/.local/lib/python3.4/site-packages/nikola/post.py", line 533, in text
    hyphenate(document, lang)
  File "…/.local/lib/python3.4/site-packages/nikola/post.py", line 947, in hyphenate
    hyphenator = pyphen.Pyphen(lang=lang)
  File "…/.local/lib/python3.4/site-packages/pyphen.py", line 246, in __init__
    filename = LANGUAGES[language_fallback(lang)]
KeyError: None
```

**Comment by Kwpolska** [comment] 2015-02-06 14:39
What languages are there on your site?

**Comment by Kwpolska** [comment] 2015-02-06 14:57
The following languages do not have hyphenation dictionaries available, resulting in this crash:

* `ar` (Arabic)
* `cz` (Czech with the **wrong name**)
* `eo` (Esperanto)
* `eu` (Basque)
* `fa` (Persian)
* `fi` (Finnish)
* `hi` (Hindi)
* `id` (Indonesian)
* `ko` (Korean)
* `pt_br` (Portuguese (Brasil)) becomes `pt` (→Portuguese (Portugal))
* `tr` (Turkish)
* `zh_cn` (Chinese (Simplified))

This needs to be fixed by ignoring hyphenation for those languages, and normalizing for Portuguese.

**Comment by devurandom** [comment] 2015-02-06 15:01
I more or less use the default `conf.py` with `DEFAULT_LANG = "de"`. I did not translate any of my posts.

**Comment by Kwpolska** [comment] 2015-02-06 15:12
Cannot reproduce *your* issue then.

Run (in the same venv): `python -c 'import pyphen; print(pyphen.LANGUAGES)'`

Make sure `de` is on the list.  If it’s not, you can get a list of all path where the correct files should reside: `python -c 'import pyphen; print(pyphen.dictionaries_roots)'`

Maybe the symlinks are broken?  What if you tried using `'de_DE'` for the thing?  Maybe you installed it weird?

```py
>>> pyphen.language_fallback('de')
'de'
>>> pyphen.LANGUAGES['de']
'/home/kwpolska/virtualenvs/nikola-py3/share/pyphen/dictionaries/hyph_de.dic'
```

```
# included dictionaries are available:
# - at <sys.prefix>/share/pyphen/dictionaries when Pyphen is installed
# - at <project_root>/dictionaries when Pyphen is not installed
# - at <pkg_resources>/share/pyphen/dictionaries when Pyphen is in an egg
```

**Comment by devurandom** [comment] 2015-02-06 15:32
```
# python3 -c 'import pyphen; print(pyphen.LANGUAGES)'
{}
# python3 -c 'import pyphen; print(pyphen.dictionaries_roots)'
('…/.local/lib/python3.4/site-packages/share/pyphen/dictionaries', '/usr/share/pyphen/dictionaries', '…/.local/lib/python3.4/site-packages/dictionaries')
# ls …/.local/lib/python3.4/site-packages/share/pyphen/dictionaries /usr/share/pyphen/dictionaries …/.local/lib/python3.4/site-packages/dictionaries
ls: cannot access …/.local/lib/python3.4/site-packages/share/pyphen/dictionaries: No such file or directory
ls: cannot access /usr/share/pyphen/dictionaries: No such file or directory
ls: cannot access …/.local/lib/python3.4/site-packages/dictionaries: No such file or directory

```

I installed Pyphen using PIP:
```
# pip3 install --user pyphen
```

**Comment by ralsina** [comment] 2015-02-06 15:35
I am guessing pyphen doesn't like being installed via --user

**Comment by devurandom** [comment] 2015-02-06 16:03
Kozea/Pyphen#10

**Comment by Kwpolska** [comment] 2015-02-06 16:04
Reopening to fix the related issue with some languages.

**Closed** 2015-02-07 10:53 UTC
Labels: bug
