### ISSUE TITLE
nikola install_theme

### ISSUE THREAD

**Issue by bretonio** [getnikola/nikola#2525] opened 2016-10-08 21:42 UTC
`nikola install_theme` for any of the listed themes returns an error `ValueError: No JSON object could be decoded` ... this occurs in `usr/lib/python2.7/json/decoder.py` line 384.

**Comment by Kwpolska** [comment] 2016-10-09 08:13
Cannot reproduce.

1. Make sure you’re running an up-to-date version of Nikola.
2. Use `nikola theme -i THEME_NAME` instead of `nikola install_theme` (although both use the same file)
3. Make sure you can access [the JSON file](https://themes.getnikola.com/v7/themes.json) from your machine. If it works from a web browser, run in your terminal:

        python -c 'import requests; print(requests.get("https://themes.getnikola.com/v7/themes.json").text)'

**Comment by ralsina** [comment] 2016-10-24 15:59
I suspect this was some connection error, or our site was down, or, literally "something". Let's close it, if there's new info we can reopen.

**Closed by ralsina** 2016-10-24 15:59 UTC
Labels: can't reproduce

**Comment by bretonio** [comment] 2016-10-31 10:42
No news. Thanks for the instructions will get right on it.
