### ISSUE TITLE
Unable to install Nikola on OSX

### ISSUE THREAD

**Issue by schwaaweb** [getnikola/nikola#3143] opened 2018-08-19 16:26 UTC
### Environment (if reporting a bug)

**Python Version:**
Python 3.6.4 |Anaconda custom (64-bit)| (default, Jan 16 2018, 12:04:33)
[GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)] on darwin

**Nikola Version:**
I'm unable to install so I'm not sure

**Operating System:**
OSX 10.13.6 :: macOS HighSierra

### Description:

I'm not sure how to get this to work. Any clues to what I should try next would be appreciated!

Thanks!
- Darwin

These are the commands I ran to try to install Nikola:

```virtualenv nikola
cd nikola
source bin/activate
pip install --upgrade pip setuptools wheel
pip install --upgrade "Nikola[extras]"
```

The final command fails here is some of the output:

```
...

copying src/watchdog/utils/unicode_paths.py -> build/lib.macosx-10.7-x86_64-3.6/watchdog/utils
  copying src/watchdog/utils/win32stat.py -> build/lib.macosx-10.7-x86_64-3.6/watchdog/utils
  running egg_info
  writing src/watchdog.egg-info/PKG-INFO
  writing dependency_links to src/watchdog.egg-info/dependency_links.txt
  writing entry points to src/watchdog.egg-info/entry_points.txt
  writing requirements to src/watchdog.egg-info/requires.txt
  writing top-level names to src/watchdog.egg-info/top_level.txt
  reading manifest file 'src/watchdog.egg-info/SOURCES.txt'
  reading manifest template 'MANIFEST.in'
  warning: no files found matching '*.h' under directory 'src'
  writing manifest file 'src/watchdog.egg-info/SOURCES.txt'
  running build_ext
  building '_watchdog_fsevents' extension
  creating build/temp.macosx-10.7-x86_64-3.6
  creating build/temp.macosx-10.7-x86_64-3.6/src
  gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/Users/darwinm/anaconda3/include -arch x86_64 -I/Users/darwinm/anaconda3/include -arch x86_64 -DWATCHDOG_VERSION_STRING="0.8.3" -DWATCHDOG_VERSION_MAJOR=0 -DWATCHDOG_VERSION_MINOR=8 -DWATCHDOG_VERSION_BUILD=3 -I/Users/darwinm/anaconda3/include/python3.6m -c src/watchdog_fsevents.c -o build/temp.macosx-10.7-x86_64-3.6/src/watchdog_fsevents.o -std=c99 -pedantic -Wall -Wextra -fPIC -Wno-error=unused-command-line-argument-hard-error-in-future
  warning: unknown warning option '-Werror=unused-command-line-argument-hard-error-in-future'; did you mean '-Werror=unused-command-line-argument'? [-Wunknown-warning-option]
  In file included from src/watchdog_fsevents.c:24:
  In file included from /System/Library/Frameworks/CoreServices.framework/Headers/CoreServices.h:23:
  In file included from /System/Library/Frameworks/CoreServices.framework/Frameworks/AE.framework/Headers/AE.h:20:
  In file included from /System/Library/Frameworks/CoreServices.framework/Frameworks/CarbonCore.framework/Headers/CarbonCore.h:208:
  In file included from /System/Library/Frameworks/CoreServices.framework/Frameworks/CarbonCore.framework/Headers/HFSVolumes.h:25:
  /usr/include/hfs/hfs_format.h:794:2: error: unknown type name 'uuid_string_t'; did you mean 'io_string_t'?
          uuid_string_t   ext_jnl_uuid;
          ^
  /usr/include/device/device_types.h:89:16: note: 'io_string_t' declared here
  typedef char                    io_string_t[512];
                                  ^
  In file included from src/watchdog_fsevents.c:24:
  In file included from /System/Library/Frameworks/CoreServices.framework/Headers/CoreServices.h:23:
  In file included from /System/Library/Frameworks/CoreServices.framework/Frameworks/AE.framework/Headers/AE.h:20:
  In file included from /System/Library/Frameworks/CoreServices.framework/Frameworks/CarbonCore.framework/Headers/CarbonCore.h:208:
  In file included from /System/Library/Frameworks/CoreServices.framework/Frameworks/CarbonCore.framework/Headers/HFSVolumes.h:25:
  /usr/include/hfs/hfs_format.h:796:20: error: use of undeclared identifier 'uuid_string_t'
          char            reserved[JIB_RESERVED_SIZE];
                                   ^
  /usr/include/hfs/hfs_format.h:787:61: note: expanded from macro 'JIB_RESERVED_SIZE'
  #define JIB_RESERVED_SIZE  ((32*sizeof(u_int32_t)) - sizeof(uuid_string_t) - 48)
                                                              ^
  src/watchdog_fsevents.c:136:63: warning: unused parameter 'stream_ref' [-Wunused-parameter]
  watchdog_FSEventStreamCallback(ConstFSEventStreamRef          stream_ref,
                                                                ^
  src/watchdog_fsevents.c:141:63: warning: unused parameter 'event_ids' [-Wunused-parameter]
                                 const FSEventStreamEventId     event_ids[])
                                                                ^
  src/watchdog_fsevents.c:334:30: warning: unused parameter 'self' [-Wunused-parameter]
  watchdog_add_watch(PyObject *self, PyObject *args)
                               ^
  src/watchdog_fsevents.c:417:32: warning: unused parameter 'self' [-Wunused-parameter]
  watchdog_read_events(PyObject *self, PyObject *args)
                                 ^
  src/watchdog_fsevents.c:466:33: warning: unused parameter 'self' [-Wunused-parameter]
  watchdog_remove_watch(PyObject *self, PyObject *watch)
                                  ^
  src/watchdog_fsevents.c:491:25: warning: unused parameter 'self' [-Wunused-parameter]
  watchdog_stop(PyObject *self, PyObject *emitter_thread)
                          ^
  src/watchdog_fsevents.c:531:10: warning: missing field 'ml_meth' initializer [-Wmissing-field-initializers]
      {NULL},
           ^
  src/watchdog_fsevents.c:602:1: warning: missing field 'm_slots' initializer [-Wmissing-field-initializers]
  };
  ^
  9 warnings and 2 errors generated.
  error: command 'gcc' failed with exit status 1

  ----------------------------------------
  Failed building wheel for watchdog
  Running setup.py clean for watchdog
  Running setup.py bdist_wheel for macfsevents ... error
  Complete output from command /Users/darwinm/Documents/LambdaSchool/17/nikola/bin/python -u -c "import setuptools, tokenize;__file__='/private/var/folders/41/dkv_flhd6qb771xwzb83k3v80000gp/T/pip-install-he6a0k3e/macfsevents/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /private/var/folders/41/dkv_flhd6qb771xwzb83k3v80000gp/T/pip-wheel-9mx1igq7 --python-tag cp36:
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.macosx-10.7-x86_64-3.6
  copying fsevents.py -> build/lib.macosx-10.7-x86_64-3.6
  running build_ext
  building '_fsevents' extension
  creating build/temp.macosx-10.7-x86_64-3.6
  gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/Users/darwinm/anaconda3/include -arch x86_64 -I/Users/darwinm/anaconda3/include -arch x86_64 -I/Users/darwinm/anaconda3/include/python3.6m -c _fsevents.c -o build/temp.macosx-10.7-x86_64-3.6/_fsevents.o
  In file included from _fsevents.c:3:
  In file included from /System/Library/Frameworks/CoreServices.framework/Headers/CoreServices.h:23:
  In file included from /System/Library/Frameworks/CoreServices.framework/Frameworks/AE.framework/Headers/AE.h:20:
  In file included from /System/Library/Frameworks/CoreServices.framework/Frameworks/CarbonCore.framework/Headers/CarbonCore.h:208:
  In file included from /System/Library/Frameworks/CoreServices.framework/Frameworks/CarbonCore.framework/Headers/HFSVolumes.h:25:
  /usr/include/hfs/hfs_format.h:794:2: error: unknown type name 'uuid_string_t'; did you mean 'io_string_t'?
          uuid_string_t   ext_jnl_uuid;
          ^
  /usr/include/device/device_types.h:89:16: note: 'io_string_t' declared here
  typedef char                    io_string_t[512];
                                  ^
  In file included from _fsevents.c:3:
  In file included from /System/Library/Frameworks/CoreServices.framework/Headers/CoreServices.h:23:
  In file included from /System/Library/Frameworks/CoreServices.framework/Frameworks/AE.framework/Headers/AE.h:20:
  In file included from /System/Library/Frameworks/CoreServices.framework/Frameworks/CarbonCore.framework/Headers/CarbonCore.h:208:
  In file included from /System/Library/Frameworks/CoreServices.framework/Frameworks/CarbonCore.framework/Headers/HFSVolumes.h:25:
  /usr/include/hfs/hfs_format.h:796:20: error: use of undeclared identifier 'uuid_string_t'
          char            reserved[JIB_RESERVED_SIZE];
                                   ^
  /usr/include/hfs/hfs_format.h:787:61: note: expanded from macro 'JIB_RESERVED_SIZE'
  #define JIB_RESERVED_SIZE  ((32*sizeof(u_int32_t)) - sizeof(uuid_string_t) - 48)
                                                              ^
  2 errors generated.
  error: command 'gcc' failed with exit status 1

  ----------------------------------------
  Failed building wheel for macfsevents
  Running setup.py clean for macfsevents
Failed to build watchdog macfsevents
Installing collected packages: macfsevents, doit, ws4py, PyYAML, argh, pathtools, watchdog, pygal, pyphen, toml, smartypants, typogrify, phpserialize, tornado, decorator, ipython-genutils, traitlets, pyzmq, jupyter-core, jupyter-client, ptyprocess, pexpect, backcall, pickleshare, simplegeneric, appnope, wcwidth, prompt-toolkit, parso, jedi, ipython, ipykernel, husl, ghp-import2, webencodings, html5lib, bleach, entrypoints, Jinja2, pandocfilters, jsonschema, nbformat, testpath, mistune, nbconvert, Send2Trash, prometheus-client, terminado, notebook, webassets, micawber, Nikola
  Running setup.py install for macfsevents ... error
    Complete output from command /Users/darwinm/Documents/LambdaSchool/17/nikola/bin/python -u -c "import setuptools, tokenize;__file__='/private/var/folders/41/dkv_flhd6qb771xwzb83k3v80000gp/T/pip-install-he6a0k3e/macfsevents/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /private/var/folders/41/dkv_flhd6qb771xwzb83k3v80000gp/T/pip-record-teislfsm/install-record.txt --single-version-externally-managed --compile --install-headers /Users/darwinm/Documents/LambdaSchool/17/nikola/include/site/python3.6/macfsevents:
    running install
    running build
    running build_py
    creating build
    creating build/lib.macosx-10.7-x86_64-3.6
    copying fsevents.py -> build/lib.macosx-10.7-x86_64-3.6
    running build_ext
    building '_fsevents' extension
    creating build/temp.macosx-10.7-x86_64-3.6
    gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/Users/darwinm/anaconda3/include -arch x86_64 -I/Users/darwinm/anaconda3/include -arch x86_64 -I/Users/darwinm/anaconda3/include/python3.6m -c _fsevents.c -o build/temp.macosx-10.7-x86_64-3.6/_fsevents.o
    In file included from _fsevents.c:3:
    In file included from /System/Library/Frameworks/CoreServices.framework/Headers/CoreServices.h:23:
    In file included from /System/Library/Frameworks/CoreServices.framework/Frameworks/AE.framework/Headers/AE.h:20:
    In file included from /System/Library/Frameworks/CoreServices.framework/Frameworks/CarbonCore.framework/Headers/CarbonCore.h:208:
    In file included from /System/Library/Frameworks/CoreServices.framework/Frameworks/CarbonCore.framework/Headers/HFSVolumes.h:25:
    /usr/include/hfs/hfs_format.h:794:2: error: unknown type name 'uuid_string_t'; did you mean 'io_string_t'?
            uuid_string_t   ext_jnl_uuid;
            ^
    /usr/include/device/device_types.h:89:16: note: 'io_string_t' declared here
    typedef char                    io_string_t[512];
                                    ^
    In file included from _fsevents.c:3:
    In file included from /System/Library/Frameworks/CoreServices.framework/Headers/CoreServices.h:23:
    In file included from /System/Library/Frameworks/CoreServices.framework/Frameworks/AE.framework/Headers/AE.h:20:
    In file included from /System/Library/Frameworks/CoreServices.framework/Frameworks/CarbonCore.framework/Headers/CarbonCore.h:208:
    In file included from /System/Library/Frameworks/CoreServices.framework/Frameworks/CarbonCore.framework/Headers/HFSVolumes.h:25:
    /usr/include/hfs/hfs_format.h:796:20: error: use of undeclared identifier 'uuid_string_t'
            char            reserved[JIB_RESERVED_SIZE];
                                     ^
    /usr/include/hfs/hfs_format.h:787:61: note: expanded from macro 'JIB_RESERVED_SIZE'
    #define JIB_RESERVED_SIZE  ((32*sizeof(u_int32_t)) - sizeof(uuid_string_t) - 48)
                                                                ^
    2 errors generated.
    error: command 'gcc' failed with exit status 1

    ----------------------------------------
Command "/Users/darwinm/Documents/LambdaSchool/17/nikola/bin/python -u -c "import setuptools, tokenize;__file__='/private/var/folders/41/dkv_flhd6qb771xwzb83k3v80000gp/T/pip-install-he6a0k3e/macfsevents/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /private/var/folders/41/dkv_flhd6qb771xwzb83k3v80000gp/T/pip-record-teislfsm/install-record.txt --single-version-externally-managed --compile --install-headers /Users/darwinm/Documents/LambdaSchool/17/nikola/include/site/python3.6/macfsevents" failed with error code 1 in /private/var/folders/41/dkv_flhd6qb771xwzb83k3v80000gp/T/pip-install-he6a0k3e/macfsevents/

```

**Comment by Kwpolska** [comment] 2018-08-19 17:42
Please look here: https://github.com/Homebrew/legacy-homebrew/issues/32587#issuecomment-56769620

In any case, this issue is not caused by Nikola and things within our control.

**Comment by schwaaweb** [comment] 2018-08-20 00:02
Thank you for the above reference. Unfortunately I'm still not clear what's causing the Nikola installation to fail.

This command below is failing:

   pip install --upgrade "Nikola[extras]"

Who's bug is causing the Nikola installation to fail?

I appreciate your patience, I'm just unclear on why this is failing.  What is my environment failing to provide to the Nikola installation?

**Comment by Kwpolska** [comment] 2018-08-20 07:48
The issue comes from `watchdog`, a dependency of Nikola, and `macfsevents`, a dependency of doit. According to the link, you have a stray header file on your system.

**Comment by Kwpolska** [comment] 2018-08-24 11:17
Closing as it’s not caused by Nikola or anything within our control.

PS. an install without [extras] *should* be successful.

**Closed by Kwpolska** 2018-08-24 11:17 UTC
Labels: someone else's bug

**Comment by schwaaweb** [comment] 2018-08-24 12:26
This is actually a bug in your documentation. In order to get this to work on my system I needed to do this:

virtualenv -p python2.7 nikola
cd nikola
source bin/activate
pip install --upgrade pip setuptools wheel
pip install --upgrade "Nikola[extras]"

It seems some of Nikola's dependencies require python2.

**Comment by Kwpolska** [comment] 2018-08-24 12:35
No. I’m using Nikola successfully on macOS with Python 3.7 from Homebrew. Version 8 will bee 3.x-only.

**Comment by schwaaweb** [comment] 2018-08-24 12:52
Well this is the only way I was able to get it installed. I'm not familiar with the project I just want to provide info for people who just want to get it running and are unable to.

The instructions provided did not work for me. 

changing:

   virtualenv nikola

to:
 
   virtualenv -p python2.7 nikola

If you can provide some insight on why this is what works on my system I would appreciate it.

Thank you
- Darwin

**Comment by Kwpolska** [comment] 2018-08-24 12:56
Have you got Homebrew installed? If yes, please try using the Homebrew python (`brew install python3`).

Another idea: what does `find /usr/local -name 'uuid.h'` list? Could you perhaps post `tree /usr/local`?

**Comment by Kwpolska** [comment] 2018-08-25 09:48
We do recommend using Homebrew Python as part of our Getting Started guide. The issue you’re facing is outside of our control, and can be only really fixed by the Anaconda developers.

**Comment by schwaaweb** [comment] 2018-08-25 10:54
OK so I'm not going to bring this up with the Anaconda developers because the solution is to add the path to Homebrew Python to the virtualenv command as I've indicated above.

Your instruction:
```
virtualenv3 nikola
Note:
  The command might be different in some environments.
  You might need to use one of the following instead:
    virtualenv
    virtualenv-3.x (where x is your Python version)
    virtualenv -p /usr/bin/python3
```
Someone with Anaconda and Homebrew would want to do this:
```
virtualenv -p /usr/local/bin/python3 nikola
```

That's it problem solved!

Cheers
- Darwin

**Comment by mUtterberg** [comment] 2018-10-26 03:35
I am also working through this issue. I did try to install without extras and it does not work in pip. I've never used homebrew, so I'll have to install that if I decide to give Nikola another try, but I don't think Mac users can install via pip at this time.
`find /usr/local -name 'uuid.h'` does not print a response.
`tree /usr/local` prints "tree: command not found" - Apparently [you need to install brew in order to make that command available](https://rschu.me/list-a-directory-with-tree-command-on-mac-os-x-3b2d4c4a4827).
Hope that helps! I use conda and pip, so I'm hesitant to add homebrew to the mix because I've heard they can conflict and cause packages to misbehave/break. I use the Anaconda installation of Jupyter Notebooks, so I really need Anaconda to work unperturbed. Is the pip package built from this repo?

**Comment by Kwpolska** [comment] 2018-10-26 11:37
@mUtterberg Please show full install log. Nikola *can* be installed via pip, at least on Homebrew’s Python. Anaconda’s might be doing something wrong, a bug report to them might be in order.

**Comment by mUtterberg** [comment] 2018-10-26 12:14
@Kwpolska I’m sorry if it came off as me suggesting pip install was entirely broken, I just wanted to echo the sentiment above that it does not work without Homebrew, which I would prefer not to install for a single package, as the packages distributed with conda are more in line with my use-case. I will definitely raise an issue with Anaconda, but I would love some guidance on what is causing the install to return 1. If I could conda install nikola, would that solve the issue? I won’t be able to post a traceback summary until my lunch break, but it was similar to the one posted here, which is why I looked to this thread for help rather than raising an issue.

**Comment by mUtterberg** [comment] 2018-10-26 17:33
Tried again with a `virtualenv --system-site-packages` to see if that would help with the path issue. My global packages have the `/anaconda3` prefix, if that's useful info.
![screen shot 2018-10-26 at 1 18 46 pm](https://user-images.githubusercontent.com/35174396/47582248-d70e8000-d921-11e8-9c72-4ff5b4a76d75.png)
Here's a screenshot of what seems like the most relevant part of the traceback.
I think it's worth explicitly stating in the instructions that the command in the latest comment from @schwaaweb may offer a solution to Anaconda Python users, many of whom would be looking into Nikola specifically for the Jupyter NB support. It would at least be nice to be able to ctrl+F for the word "Anaconda" appearing somewhere on the installation page, as there is an existing workaround that works for this use case.

**Comment by Kwpolska** [comment] 2018-10-26 18:35
1. This looks like an `[extras]` install to me, since it mentions the `watchdog` package. Installing without extras means running `pip install Nikola` instead of `pip install 'Nikola[extras]`'
2. I installed Anaconda 5.3 on macOS Mojave. Installing Nikola succeeded, even with `[extras]`. My system has Xcode and xcode-select installed. Which of these are on your system? (Xcode → /Applications/Xcode.app exists; xcode-select → running `xcode-select --install` in Terminal says it’s already installed)
