### ISSUE TITLE
rsync deployment is successful but exception and traceback result

### ISSUE THREAD

**Issue by neildarlow** [getnikola/nikola#3505] opened 2021-01-27 15:35 UTC
### Environment

**Python Version: 3.8.2-0ubuntu2**

**Nikola Version: v8.1.2**

**Operating System: Linux Mint 20.1 Cinnamon**

### Description: Performing rsync deployment results in traceback.

Nikola installed as described in Getting Started Guide.  
The deployment is successful but I receive the following traceback:

[2021-01-27 15:23:47] INFO: deploy: Successful deployment  
Traceback (most recent call last):  
  File "/home/neil/nikola/lib/python3.8/site-packages/doit/doit_cmd.py", line 190, in run  
    return command.parse_execute(args)  
  File "/home/neil/nikola/lib/python3.8/site-packages/doit/cmd_base.py", line 150, in parse_execute  
    return self.execute(params, args)  
  File "/home/neil/nikola/lib/python3.8/site-packages/nikola/plugin_categories.py", line 145, in execute  
    return self._execute(options, args)  
  File "/home/neil/nikola/lib/python3.8/site-packages/nikola/plugins/command/deploy.py", line 99, in _execute  
    self._emit_deploy_event(last_deploy, new_deploy, clean, undeployed_posts)  
UnboundLocalError: local variable 'clean' referenced before assignment

EDIT: Formatted traceback a little.

**Comment by Kwpolska** [comment] 2021-01-27 22:41
Duplicate of #3502, #3500 and #3479. Please search existing issues before creating a new one.

**Closed by Kwpolska** 2021-01-27 22:41 UTC
Labels: bug, duplicate

**Comment by neildarlow** [comment] 2021-01-28 08:01
Oh my bad. To be fair the default search only searches open bugs and the duplicates have been closed.
