### ISSUE TITLE
output/assets/css/code.css task is always outdated

### ISSUE THREAD

**Issue by Aeyoun** [getnikola/nikola#2120] opened 2015-09-25 11:50 UTC
and orphaned.

**Comment by ralsina** [comment] 2015-09-25 12:45
The orphan thing I thought I fixed?

**Comment by Aeyoun** [comment] 2015-09-25 12:52
Installed master just now.

    d:~/blog$ nikola build
    Scanning posts................done!
    .  copy_assets:output/assets/css/code.css
    d:~/blog$ nikola build
    Scanning posts................done!
    .  copy_assets:output/assets/css/code.css

**Comment by ralsina** [comment] 2015-09-25 12:56
grmbl.

**Comment by ralsina** [comment] 2015-11-04 15:21
I must say I am totally stumped and unable to reproduce this one.

**Comment by Aeyoun** [comment] 2015-11-04 21:41
I can’t reproduce it on demand either. It happens all the time given that I’m not trying to reproduce it. If I leave auto running it will just keep rebuilding indefinitely.

**Comment by Kwpolska** [comment] 2016-02-11 13:12
Closing as *cannot reproduce*.

**Closed by Kwpolska** 2016-02-11 13:12 UTC
Labels: bug, can't reproduce
