### ISSUE TITLE
Remove renders of files no longer present

### ISSUE THREAD

**Issue by StyXman** [getnikola/nikola#2147] opened 2015-10-18 10:49 UTC
Posts and images in galleries can be removed because reasons, but Nikola does not detect their rendering being stale. It should remove those.

**Comment by Kwpolska** [comment] 2015-10-18 10:51
We don’t do it automatically, because some people might still want to refer to them. We don’t delete any files by default.  Look at `nikola orphans`, `nikola check -f` and `nikola check --clean-files`.

**Comment by Aeyoun** [comment] 2015-10-18 11:51
What could be discusses is whether Nikola should volunteer info about orphaned items during deployment, status check, or similar actions.

**Comment by Aeyoun** [comment] 2015-10-18 11:53
The same issue keeps popping up.

**Comment by ralsina** [comment] 2015-10-23 17:32
The problem is, checking for orphans is a rather expensive thing in large sites. It takes ~12 seconds in my rather fast computer (i7, SSD) so adding it makes nikola *much* slower.

**Comment by StyXman** [comment] 2015-10-23 17:53
Not quite true, because you're already scanning the source directory and traversing the destination, so in theory directory contents should already be there in the cache. The only thing preventing doing it really fast is the fact that right now either the gallery plugin or the internals of nikola is reading all the files, either to calculate a hash or reading their metadata. But that's material for another bug :)

Meanwhile, the algo is not that difficult; in fact, i have something like that in another project, which implements one of rsync's deleting modes (the inline one, `--delete`):

https://github.com/StyXman/elevation/blob/master/push-zagato.py#L43

**Comment by ralsina** [comment] 2015-10-26 15:13
Maybe for orphans / check we should switch --check_file_uptodate to timestamp. Sure would be faster with image galleries...

**Comment by ralsina** [comment] 2015-11-01 00:03
Ok, so nikola already offers a way to remove orphaned files. If a user really really wants not to upload those, add it as the 1st step in ``nikola deploy`` and that's it. 

If someone wants to add it to nikola status it's easy (if slow in large sites), and can be requested separately.

If someone wants the build process to remove those as a final step, it's also doable, but should be done with extreme care and hidden behind a flag, disabled by default, and I am not that person :-)

Finally, since this is tagged wontfix, closing.

**Closed by ralsina** 2015-11-01 00:03 UTC
Labels: question, wontfix
