### ISSUE TITLE
Error obtaining title from document in reSt in v8

### ISSUE THREAD

**Issue by Kwpolska** [getnikola/nikola#2987] opened 2018-03-15 19:33 UTC
reSt pages with title in the document but no title in the metadata have the slug as title.

This used to work correctly in v7 (document title was used), but it doesn't in v8 (slug or filename is used).

**Comment by Kwpolska** [comment] 2018-03-15 19:47
The Handbook has a `.. title: The Nikola Handbook` line as well.

**Comment by ralsina** [comment] 2018-03-15 20:52
So does creating-a-theme.txt:

```
.. title: Creating a Theme
.. slug: creating-a-theme
.. date: 2015-05-28 18:46:48 UTC
.. tags:
.. category:
.. link:
.. description:
.. type: text

Creating a Theme
================

```

```
.. title: The Nikola Handbook
.. slug: handbook
.. date: 2012-03-30 23:00:00 UTC-03:00
.. link:
.. description:
.. tags: mathjax
.. author: The Nikola Team

The Nikola Handbook
===================

```

**Comment by ralsina** [comment] 2018-03-15 20:52
Honestly I have no idea why they look different.

**Comment by Kwpolska** [comment] 2018-03-15 20:57
It looks different [on the site](https://getnikola.com/creating-a-theme.txt).

**Comment by ralsina** [comment] 2018-03-15 21:03
Annnnnd that explains it. I suppose this will go away once we redo the site for v8 one of these years. I will do a quick rebuild fixing that.

**Comment by ralsina** [comment] 2018-03-15 21:09
Fixed on the site, I am pushing it in the v7 branch as well

**Comment by ralsina** [comment] 2018-03-15 21:13
Still need to fix the root cause.

**Comment by ralsina** [comment] 2018-03-17 16:17
So, it seems we either don't have or it's not using, a metadata extractor for reSt data.

**Comment by Kwpolska** [comment] 2018-03-17 16:18
This one is supposed to be used: https://github.com/getnikola/nikola/blob/master/nikola/plugins/compile/rest/__init__.py#L65

Perhaps there’s some issue with priorities, or with merging output of different extractors?

**Comment by ralsina** [comment] 2018-03-17 16:20
Don't know, am trying to see :-)

**Comment by ralsina** [comment] 2018-03-17 16:26
Looks like this is False and should be True

```
metadata_extractors.check_conditions(post, post.source_path, post.compiler.metadata_conditions, config, None))
```

**Comment by Kwpolska** [comment] 2018-04-25 20:44
The `compiler_meta_is_fallbackish` would have fixed this after enabling `USE_REST_DOCINFO_METADATA`, but then it outputs a ton of errors:
```
Scanning posts.[2018-04-25T20:43:15Z] ERROR: rest: [posts/1.rst:20] "handbook" slug doesn't exist.
[2018-04-25T20:43:15Z] ERROR: rest: [posts/1.rst:23] "listings-demo" slug doesn't exist.
[2018-04-25T20:43:15Z] ERROR: rest: [posts/1.rst:24] "dr-nikolas-vendetta" slug doesn't exist.
....[2018-04-25T20:43:15Z] ERROR: rest: [pages/theming.rst:21] "creating-a-theme" slug doesn't exist.
[2018-04-25T20:43:16Z] ERROR: rest: [pages/manual.rst:1308] "extending" slug doesn't exist.
[2018-04-25T20:43:16Z] ERROR: rest: [pages/manual.rst:1459] "theming" slug doesn't exist.
[2018-04-25T20:43:16Z] ERROR: rest: [pages/manual.rst:1473] "theming" slug doesn't exist.
[2018-04-25T20:43:16Z] ERROR: rest: [pages/manual.rst:1615] "theming" slug doesn't exist.
[2018-04-25T20:43:16Z] ERROR: rest: [pages/manual.rst:1615] "creating-a-theme" slug doesn't exist.
[2018-04-25T20:43:17Z] ERROR: rest: [pages/manual.rst:2627] "creating-a-theme" slug doesn't exist.
[2018-04-25T20:43:17Z] ERROR: rest: [pages/manual.rst:2637] "creating-a-theme" slug doesn't exist.
[2018-04-25T20:43:17Z] ERROR: rest: [pages/manual.rst:2881] "extending" slug doesn't exist.
[2018-04-25T20:43:17Z] ERROR: rest: [pages/creating-a-theme.rst:20] "theming" slug doesn't exist.
[2018-04-25T20:43:17Z] ERROR: rest: [pages/creating-a-theme.rst:831] "theming" slug doesn't exist.
...done!
```

The pages seem to work though.  This probably needs more work.

**Closed** 2018-04-26 00:16 UTC
Labels: BLOCKER, bug
