### ISSUE TITLE
Build fails silently if jinja not available

### ISSUE THREAD

**Issue by akhmerov** [getnikola/nikola#1916] opened 2015-07-28 17:42 UTC
Right now `bootstrap3-jinja` is one of the built-in themes, but `jinja2` isn't in pip requirements. However if jinja isn't available trying to build a site with this theme will show no errors/warnings, only copying some assets will not happen.

To reproduce: 
* install nikola in an empty virtual environment
* make a demo site
* switch theme to bootstrap3-jinja
* build & serve

Silent build error is very hard to pin down, and therefore I believe this is a bug.

**Comment by ralsina** [comment] 2015-07-28 17:46
I just tried this and I can't reproduce:

```
$ nikola build
[2015-07-28T17:46:01Z] ERROR: Nikola: In order to use this theme, you must install the "jinja2" Python package.
[2015-07-28T17:46:01Z] ERROR: Nikola: Exiting due to missing dependencies.
```

**Comment by akhmerov** [comment] 2015-07-28 17:50
I'll investigate the exact circumstances.

**Comment by akhmerov** [comment] 2015-07-29 12:26
Cannot reproduce in pip, reported in Debian: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=793953

**Comment by Kwpolska** [comment] 2015-07-29 15:50
Debian ruined the theme by deleting (or, at least, not shipping) the following important files:

```
/usr/lib/python2.7/dist-packages/nikola/data/themes/bootstrap3-jinja/assets/css/bootstrap.css
/usr/lib/python2.7/dist-packages/nikola/data/themes/bootstrap3-jinja/assets/css/bootstrap.min.css
/usr/lib/python2.7/dist-packages/nikola/data/themes/bootstrap3-jinja/assets/css/bootstrap-theme.css
/usr/lib/python2.7/dist-packages/nikola/data/themes/bootstrap3-jinja/assets/css/bootstrap-theme.min.css
```

Closing as *someone else’s bug*.  Please don’t use the Debian package to install Nikola.

**Closed by Kwpolska** 2015-07-29 15:50 UTC
Labels: someone else's bug
