### ISSUE TITLE
Build problems between Windows and Travis CI environment

### ISSUE THREAD

**Issue by sebastian-schmidt** [getnikola/nikola#1657] opened 2015-04-16 13:49 UTC
Hi,

I try to implement a deploy system via Travis CI and GH-pages.
I get this error  log:
https://s3.amazonaws.com/archive.travis-ci.org/jobs/58745779/log.txt

`Nikola build` works fine on my win 7 machine with python 32 bit 3.4.
I read some other issue with this error and disabled some things conf.py and now it works. 

```
-    "markdown": ('.md', '.mdown', '.markdown'),
-    "textile": ('.textile',),
-    "txt2tags": ('.t2t',),
-    "bbcode": ('.bb',),
-    "wiki": ('.wiki',),
-    "ipynb": ('.ipynb',),
-    "html": ('.html', '.htm'),
+    #"markdown": ('.md', '.mdown', '.markdown'),
+    #"textile": ('.textile',),
+    #"txt2tags": ('.t2t',),
+    #"bbcode": ('.bb',),
+    #"wiki": ('.wiki',),
+    #"ipynb": ('.ipynb',),
+    #"html": ('.html', '.htm'),
     # PHP files are rendered the usual way (i.e. with the full templates).
     # The resulting files have .php extensions, making it possible to run
     # them without reconfiguring your server to recognize them.
-    "php": ('.php',),
+    #"php": ('.php',),
     # Pandoc detects the input from the source filename
     # but is disabled by default as it would conflict
     # with many of the others.
 @@ -255,7 +255,7 @@
 # If this is set to False, then posts that are not translated to a language
 # LANG will not be visible at all in the pages in that language.
 # Formerly known as HIDE_UNTRANSLATED_POSTS (inverse)
-# SHOW_UNTRANSLATED_POSTS = True
+SHOW_UNTRANSLATED_POSTS = False
 
 # Nikola supports logo display.  If you have one, you can put the URL here.
 # Final output is <img src="LOGO_URL" id="logo" alt="BLOG_TITLE">.
 @@ -751,7 +751,7 @@
 SHOW_SOURCELINK = False
 # Copy the source files for your pages?
 # Setting it to False implies SHOW_SOURCELINK = False
-# COPY_SOURCES = True
+COPY_SOURCES = False
```
This still didn't work. Finally i deleted the listing-demo.rst and running fine now, i.e. i can edit .rst on github and after travis sync the changes are online.
Not sure what to make of it.
Thanks for nikola :-)

**Comment by punchagan** [comment] 2015-04-16 14:11
It looks like the issue is with having your `.doit.db` and/or `cache` from windows committed to the repo. I cloned your [repo](https://github.com/sebastian-schmidt/blog) and was able to build it successfully on Linux, after removing the db and the cache.

**Comment by sebastian-schmidt** [comment] 2015-04-16 14:18
thanks, is there a command that forces a rebuild of the cache or should i put it on gitignore?

**Comment by Kwpolska** [comment] 2015-04-16 14:21
Just use `.gitignore`.

**Closed by Kwpolska** 2015-04-16 14:21 UTC
Labels: user error, windows
