### ISSUE TITLE
"plugin" command not working on v8.3.0

### ISSUE THREAD

**Issue by cybervegan** [getnikola/nikola#3759] opened 2024-02-18 19:15 UTC
### Environment

**Python Version:** Python 3.11.2

**Nikola Version:** 8.3.0

**Operating System:** Debian Bookworm on both x86 64bit, and DietPi Bookworm on aarch64 (Raspberry Pi 4)

### Description:

Invoking the "plugin" command on Nikola v 8.3.0 returns an error message:

$ nikola plugin
[2024-02-18 15:59:31] ERROR: Nikola: Unknown command plugin
[2024-02-18 15:59:31] INFO: Nikola: Did you mean "clean"?

Reverting to prior version (8.2.4) allows the command to succeed.

**Comment by Kwpolska** [comment] 2024-02-18 19:28
Duplicate of #3736. You can apply the fix from cec44aeb445161096303f1abc2df9c0980ab14cb. Version 8.3.1 was supposed to come out some time ago, but I didn’t have time to get that done.

**Closed by Kwpolska** 2024-02-18 19:28 UTC
Labels: bug, duplicate

**Comment by cybervegan** [comment] 2024-02-18 19:29
Ok, thanks. I did search issues for prior fixes, but didn't see one.
