### ISSUE TITLE
`<base href="">` generated incorrectly

### ISSUE THREAD

**Issue by OvermindDL1** [getnikola/nikola#2649] opened 2017-01-27 18:42 UTC
The `<base href>` in the `<head>` is being generated wrong on some pages.

For example, in my `/tags/index.html` file (via `conf.py` entry of `TAGS_INDEX_PATH = "tags/index"`) the base element is:
```html
<base href="http://mysite.com/tags%5Cindex.html">
```
The `%5C` is causing all relative links on this page to fail, no tag sections can be accessed from here.

```
$ nikola --version
Nikola v7.8.3
```

**Comment by Kwpolska** [comment] 2017-01-27 19:08
I cannot reproduce with v7.8.3 on macOS, this is what I get:

```html
<base href="https://example.com/tags/index.html">
```

But do you really need the `<base>` tags? Experience shows you don’t.

**Comment by OvermindDL1** [comment] 2017-01-27 19:32
> But do you really need the `<base>` tags? Experience shows you don’t.

Not really and I have it disabled, it was just a bug that I ran across and was able to reliably reproduce.  Feel free to `git clone https://github.com/OvermindDL1/overminddl1.github.io.git`, adjust the conf.py to re-enable the base element, then `nikola build`, the `tags/index.html` that is generated is wrong.  Also, why do I have to mark it as `tags/index` to generate a `tags/index.html`?  The full name would be better in the config.

**Comment by ralsina** [comment] 2017-01-27 19:43
```
TAGS_INDEX_PATH = "tags/index"
```

That doesn't look right to me. TAGS_INDEX_PATH is supposed to be either a filename or a full path relative to TAG_PATH

**Comment by Kwpolska** [comment] 2017-01-27 19:58
I still can’t reproduce with your site:

```html
<base href="http://blog.overminddl1.com/tags/">
```

Make sure lxml and other dependencies of Nikola are up-to-date.

**Comment by OvermindDL1** [comment] 2017-01-27 21:23
> That doesn't look right to me. TAGS_INDEX_PATH is supposed to be either a filename or a full path relative to TAG_PATH

That was my thinking, you'd think it would be a full path so I should put `tags/index.html`, however if I do that then it generates a `tags/index.html.html` in the output directory...

> Make sure lxml and other dependencies of Nikola are up-to-date.

Hmm, I did that this morning, and just tried again now but it is currently saying "Requirement already up-to-date", I've tried to upgrade every package I see through `pip` that I have, but no change.

I am on Windows here (though I usually use linux), perhaps that is affecting things (maybe it thinks the `/` is an invalid path-sep on Windows so it is encoding it instead of leaving it alone as it should?).

**Comment by felixfontein** [comment] 2017-01-29 20:36
Hmm, the generation of `tags/index.html.html` is clearly a bug. Should be fixed in PR #2652.

**Comment by Kwpolska** [comment] 2017-04-15 13:58
@OvermindDL1 Are you still experiencing this bug?

**Comment by ralsina** [comment] 2017-05-06 22:42
3 weeks without reply and could not reproduce... closing, can reopen if it happens again.

**Closed by ralsina** 2017-05-06 22:42 UTC
Labels: can't reproduce

**Comment by OvermindDL1** [comment] 2017-05-08 15:23
Sorry, hard to to test currently, will re-open if any issues.  As stated, I have that disabled so it is not in my main set.  ^.^
