### ISSUE TITLE
test_write_content_does_not_detroy_text doesn't pass

### ISSUE THREAD

**Issue by fabaff** [getnikola/nikola#3554] opened 2021-05-29 08:27 UTC
### Environment

**Python Version:**
3.8.9

**Nikola Version:**
8.1.3

**Operating System:**
NixOS

### Description:

During the package build process `test_write_content_does_not_detroy_text` fails.

```bash
============================= test session starts ==============================
platform linux -- Python 3.8.9, pytest-6.2.3, py-1.10.0, pluggy-0.13.1
rootdir: /build/Nikola-8.1.3, configfile: setup.cfg
collected 497 items / 4 deselected / 493 selected                              

tests/test_command_import_wordpress.py ...............F......            [  4%]
tests/test_command_import_wordpress_translation.py ..........            [  6%]
[...]
=================================== FAILURES ===================================
___________________ test_write_content_does_not_detroy_text ____________________

import_command = <nikola.plugins.command.import_wordpress.CommandImportWordpress object at 0x7ffff3829c70>

    def test_write_content_does_not_detroy_text(import_command):
        content = b"""FOO"""
        open_mock = mock.mock_open()
        with mock.patch("nikola.plugins.basic_import.open", open_mock, create=True):
            import_command.write_content("some_file", content)

>       open_mock.assert_has_calls(
            [
                mock.call(u"some_file", u"wb+"),
                mock.call().__enter__(),
                mock.call().write(b"<html><body><p>FOO</p></body></html>"),
                mock.call().__exit__(None, None, None),
            ]
        )

tests/test_command_import_wordpress.py:343:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <MagicMock name='open' spec='builtin_function_or_method' id='140737278811680'>
calls = [call('some_file', 'wb+'), call().__enter__(), call().write(b'<html><body><p>FOO</p></body></html>'), call().__exit__(None, None, None)]
any_order = False

    def assert_has_calls(self, calls, any_order=False):
        """assert the mock has been called with the specified calls.
        The `mock_calls` list is checked for the calls.
    
        If `any_order` is False (the default) then the calls must be
        sequential. There can be extra calls before or after the
        specified calls.
    
        If `any_order` is True then the calls can be in any order, but
        they must all appear in `mock_calls`."""
        expected = [self._call_matcher(c) for c in calls]
        cause = next((e for e in expected if isinstance(e, Exception)), None)
        all_calls = _CallList(self._call_matcher(c) for c in self.mock_calls)
        if not any_order:
            if expected not in all_calls:
                if cause is None:
                    problem = 'Calls not found.'
                else:
                    problem = ('Error processing expected calls.\n'
                               'Errors: {}').format(
                                   [e if isinstance(e, Exception) else None
                                    for e in expected])
>               raise AssertionError(
                    f'{problem}\n'
                    f'Expected: {_CallList(calls)}'
                    f'{self._calls_repr(prefix="Actual").rstrip(".")}'
                ) from cause
E               AssertionError: Calls not found.
E               Expected: [call('some_file', 'wb+'),
E                call().__enter__(),
E                call().write(b'<html><body><p>FOO</p></body></html>'),
E                call().__exit__(None, None, None)]
E               Actual: [call('some_file', 'wb+'),
E                call().__enter__(),
E                call().write(b'<html><body><p>FOO</p></body></html>\n'),
E                call().__exit__(None, None, None)]

/nix/store/66fbv9mmx1j4hrn9y06kcp73c3yb196r-python3-3.8.9/lib/python3.8/unittest/mock.py:950: AssertionError
=============================== warnings summary ===============================
```

Thanks for taking a look.

**Comment by Kwpolska** [comment] 2021-05-29 08:34
Duplicate of #3553. Please search for existing issues before creating a new one.

This is a bug in libxml2, which has been fixed recently: https://gitlab.gnome.org/GNOME/libxml2/-/issues/255

**Closed by Kwpolska** 2021-05-29 08:34 UTC
Labels: bug, duplicate, someone else's bug
